# coding: utf-8

"""
    BEAI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.67.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateInterviewRequestCandidate(BaseModel):
    """
    CreateInterviewRequestCandidate
    """ # noqa: E501
    candidate_ref: Annotated[str, Field(strict=True, max_length=255)]
    display_name: Annotated[str, Field(strict=True, max_length=255)]
    email: Annotated[str, Field(strict=True, max_length=255)] = Field(description="Valid email address, at most 255 characters.")
    external_id: Optional[Annotated[int, Field(le=9007199254740991, strict=True, ge=1)]] = None
    language: Optional[Annotated[str, Field(strict=True)]] = Field(default=None, description="ISO 639-1 language code: two lowercase letters, for example `it`.")
    source: Optional[Annotated[str, Field(strict=True, max_length=180)]] = None
    __properties: ClassVar[List[str]] = ["candidate_ref", "display_name", "email", "external_id", "language", "source"]

    @field_validator('language', mode="before")
    def language_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if value is None:
            return value

        if isinstance(value, str) and not re.match(r"^[a-z]{2}$", value):
            raise ValueError(r"must validate the regular expression /^[a-z]{2}$/")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateInterviewRequestCandidate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if external_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_id is None and "external_id" in self.model_fields_set:
            _dict['external_id'] = None

        # set to None if language (nullable) is None
        # and model_fields_set contains the field
        if self.language is None and "language" in self.model_fields_set:
            _dict['language'] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['source'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateInterviewRequestCandidate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "candidate_ref": obj.get("candidate_ref"),
            "display_name": obj.get("display_name"),
            "email": obj.get("email"),
            "external_id": obj.get("external_id"),
            "language": obj.get("language"),
            "source": obj.get("source")
        })
        return _obj


