# coding: utf-8

"""
    BEAI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.68.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PublicApiWebhooksDeliveriesIndex200ResponseDataInner(BaseModel):
    """
    PublicApiWebhooksDeliveriesIndex200ResponseDataInner
    """ # noqa: E501
    attempt_count: StrictInt
    candidate_ref: StrictStr
    created_at: StrictStr
    delivered_at: Optional[StrictStr]
    event_type: StrictStr
    id: StrictStr
    interview_id: StrictStr
    last_attempt_at: Optional[StrictStr]
    last_response_status: Optional[StrictInt]
    max_attempts: StrictInt
    next_attempt_at: Optional[StrictStr]
    payload_version: StrictStr
    project_id: StrictStr
    status: StrictStr
    target_url: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["attempt_count", "candidate_ref", "created_at", "delivered_at", "event_type", "id", "interview_id", "last_attempt_at", "last_response_status", "max_attempts", "next_attempt_at", "payload_version", "project_id", "status", "target_url"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PublicApiWebhooksDeliveriesIndex200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if delivered_at (nullable) is None
        # and model_fields_set contains the field
        if self.delivered_at is None and "delivered_at" in self.model_fields_set:
            _dict['delivered_at'] = None

        # set to None if last_attempt_at (nullable) is None
        # and model_fields_set contains the field
        if self.last_attempt_at is None and "last_attempt_at" in self.model_fields_set:
            _dict['last_attempt_at'] = None

        # set to None if last_response_status (nullable) is None
        # and model_fields_set contains the field
        if self.last_response_status is None and "last_response_status" in self.model_fields_set:
            _dict['last_response_status'] = None

        # set to None if next_attempt_at (nullable) is None
        # and model_fields_set contains the field
        if self.next_attempt_at is None and "next_attempt_at" in self.model_fields_set:
            _dict['next_attempt_at'] = None

        # set to None if target_url (nullable) is None
        # and model_fields_set contains the field
        if self.target_url is None and "target_url" in self.model_fields_set:
            _dict['target_url'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PublicApiWebhooksDeliveriesIndex200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "attempt_count": obj.get("attempt_count"),
            "candidate_ref": obj.get("candidate_ref"),
            "created_at": obj.get("created_at"),
            "delivered_at": obj.get("delivered_at"),
            "event_type": obj.get("event_type"),
            "id": obj.get("id"),
            "interview_id": obj.get("interview_id"),
            "last_attempt_at": obj.get("last_attempt_at"),
            "last_response_status": obj.get("last_response_status"),
            "max_attempts": obj.get("max_attempts"),
            "next_attempt_at": obj.get("next_attempt_at"),
            "payload_version": obj.get("payload_version"),
            "project_id": obj.get("project_id"),
            "status": obj.get("status"),
            "target_url": obj.get("target_url")
        })
        return _obj


