# coding: utf-8

"""
    BEAI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.67.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from beai.models.public_interview_project_framework_version import PublicInterviewProjectFrameworkVersion
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PublicInterviewProject(BaseModel):
    """
    PublicInterviewProject
    """ # noqa: E501
    assessment_type: StrictStr
    avatar_display_name: StrictStr
    competencies: List[Any]
    created_at: StrictStr
    exit_redirect_url: Optional[StrictStr]
    framework_version: PublicInterviewProjectFrameworkVersion
    id: StrictStr
    language: StrictStr
    name: StrictStr
    nudge_min_chars: Optional[StrictInt]
    pause_every_n_competencies: Optional[StrictInt]
    role_code: Optional[StrictStr]
    slug: StrictStr
    status: StrictStr
    updated_at: StrictStr
    __properties: ClassVar[List[str]] = ["assessment_type", "avatar_display_name", "competencies", "created_at", "exit_redirect_url", "framework_version", "id", "language", "name", "nudge_min_chars", "pause_every_n_competencies", "role_code", "slug", "status", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PublicInterviewProject from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of framework_version
        if self.framework_version:
            _dict['framework_version'] = self.framework_version.to_dict()
        # set to None if exit_redirect_url (nullable) is None
        # and model_fields_set contains the field
        if self.exit_redirect_url is None and "exit_redirect_url" in self.model_fields_set:
            _dict['exit_redirect_url'] = None

        # set to None if nudge_min_chars (nullable) is None
        # and model_fields_set contains the field
        if self.nudge_min_chars is None and "nudge_min_chars" in self.model_fields_set:
            _dict['nudge_min_chars'] = None

        # set to None if pause_every_n_competencies (nullable) is None
        # and model_fields_set contains the field
        if self.pause_every_n_competencies is None and "pause_every_n_competencies" in self.model_fields_set:
            _dict['pause_every_n_competencies'] = None

        # set to None if role_code (nullable) is None
        # and model_fields_set contains the field
        if self.role_code is None and "role_code" in self.model_fields_set:
            _dict['role_code'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PublicInterviewProject from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "assessment_type": obj.get("assessment_type"),
            "avatar_display_name": obj.get("avatar_display_name"),
            "competencies": obj.get("competencies"),
            "created_at": obj.get("created_at"),
            "exit_redirect_url": obj.get("exit_redirect_url"),
            "framework_version": PublicInterviewProjectFrameworkVersion.from_dict(obj["framework_version"]) if obj.get("framework_version") is not None else None,
            "id": obj.get("id"),
            "language": obj.get("language"),
            "name": obj.get("name"),
            "nudge_min_chars": obj.get("nudge_min_chars"),
            "pause_every_n_competencies": obj.get("pause_every_n_competencies"),
            "role_code": obj.get("role_code"),
            "slug": obj.get("slug"),
            "status": obj.get("status"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


