# coding: utf-8

"""
    BEAI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.68.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from beai.models.public_api_interviews_scoring200_response_competencies_value_behaviors_inner import PublicApiInterviewsScoring200ResponseCompetenciesValueBehaviorsInner
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PublicApiInterviewsScoring200ResponseCompetenciesValue(BaseModel):
    """
    PublicApiInterviewsScoring200ResponseCompetenciesValue
    """ # noqa: E501
    behaviors: List[PublicApiInterviewsScoring200ResponseCompetenciesValueBehaviorsInner]
    reliability: Union[StrictFloat, StrictInt]
    score: Optional[Union[StrictFloat, StrictInt]]
    unscorable_reason: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["behaviors", "reliability", "score", "unscorable_reason"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PublicApiInterviewsScoring200ResponseCompetenciesValue from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in behaviors (list)
        _items = []
        if self.behaviors:
            for _item_behaviors in self.behaviors:
                _items.append(_item_behaviors.to_dict() if _item_behaviors is not None else None)
            _dict['behaviors'] = _items
        # set to None if score (nullable) is None
        # and model_fields_set contains the field
        if self.score is None and "score" in self.model_fields_set:
            _dict['score'] = None

        # set to None if unscorable_reason (nullable) is None
        # and model_fields_set contains the field
        if self.unscorable_reason is None and "unscorable_reason" in self.model_fields_set:
            _dict['unscorable_reason'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PublicApiInterviewsScoring200ResponseCompetenciesValue from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "behaviors": [PublicApiInterviewsScoring200ResponseCompetenciesValueBehaviorsInner.from_dict(_item) for _item in obj["behaviors"]] if obj.get("behaviors") is not None else None,
            "reliability": obj.get("reliability"),
            "score": obj.get("score"),
            "unscorable_reason": obj.get("unscorable_reason")
        })
        return _obj


