# coding: utf-8

"""
    BEAI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.67.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PublicApiExportsIndex200ResponseDataInner(BaseModel):
    """
    PublicApiExportsIndex200ResponseDataInner
    """ # noqa: E501
    checksum_sha256: Optional[StrictStr]
    completed_at: Optional[StrictStr]
    created_at: StrictStr
    download_expires_at: Optional[StrictStr]
    download_url: Optional[StrictStr]
    failure_reason: Optional[StrictStr]
    format: StrictStr
    var_from: Optional[StrictStr] = Field(alias="from")
    id: StrictStr
    livemode: StrictBool
    record_count: Optional[StrictInt]
    scope: StrictStr
    size_bytes: Optional[StrictInt]
    status: StrictStr
    to: Optional[StrictStr]
    __properties: ClassVar[List[str]] = ["checksum_sha256", "completed_at", "created_at", "download_expires_at", "download_url", "failure_reason", "format", "from", "id", "livemode", "record_count", "scope", "size_bytes", "status", "to"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PublicApiExportsIndex200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if checksum_sha256 (nullable) is None
        # and model_fields_set contains the field
        if self.checksum_sha256 is None and "checksum_sha256" in self.model_fields_set:
            _dict['checksum_sha256'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completed_at'] = None

        # set to None if download_expires_at (nullable) is None
        # and model_fields_set contains the field
        if self.download_expires_at is None and "download_expires_at" in self.model_fields_set:
            _dict['download_expires_at'] = None

        # set to None if download_url (nullable) is None
        # and model_fields_set contains the field
        if self.download_url is None and "download_url" in self.model_fields_set:
            _dict['download_url'] = None

        # set to None if failure_reason (nullable) is None
        # and model_fields_set contains the field
        if self.failure_reason is None and "failure_reason" in self.model_fields_set:
            _dict['failure_reason'] = None

        # set to None if var_from (nullable) is None
        # and model_fields_set contains the field
        if self.var_from is None and "var_from" in self.model_fields_set:
            _dict['from'] = None

        # set to None if record_count (nullable) is None
        # and model_fields_set contains the field
        if self.record_count is None and "record_count" in self.model_fields_set:
            _dict['record_count'] = None

        # set to None if size_bytes (nullable) is None
        # and model_fields_set contains the field
        if self.size_bytes is None and "size_bytes" in self.model_fields_set:
            _dict['size_bytes'] = None

        # set to None if to (nullable) is None
        # and model_fields_set contains the field
        if self.to is None and "to" in self.model_fields_set:
            _dict['to'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PublicApiExportsIndex200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "checksum_sha256": obj.get("checksum_sha256"),
            "completed_at": obj.get("completed_at"),
            "created_at": obj.get("created_at"),
            "download_expires_at": obj.get("download_expires_at"),
            "download_url": obj.get("download_url"),
            "failure_reason": obj.get("failure_reason"),
            "format": obj.get("format"),
            "from": obj.get("from"),
            "id": obj.get("id"),
            "livemode": obj.get("livemode"),
            "record_count": obj.get("record_count"),
            "scope": obj.get("scope"),
            "size_bytes": obj.get("size_bytes"),
            "status": obj.get("status"),
            "to": obj.get("to")
        })
        return _obj


