# coding: utf-8

"""
    BEAI

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.67.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from beai.models.public_interview_progress import PublicInterviewProgress
from beai.models.public_interview_project import PublicInterviewProject
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class PublicInterview(BaseModel):
    """
    PublicInterview
    """ # noqa: E501
    candidate_ref: StrictStr
    completed_at: Optional[StrictStr]
    created_at: StrictStr
    display_name: StrictStr
    email: StrictStr
    exit_redirect_url: Optional[StrictStr]
    external_id: Optional[StrictInt] = Field(description="The calling system's own numeric identifier for this candidate, as supplied when the interview was created; `null` when none was given.")
    hosted_url: Optional[StrictStr] = Field(description="Always `null` on a read: the hosted interview URL is returned only together with a freshly issued session token.")
    id: StrictStr
    language: StrictStr
    livemode: StrictBool
    metadata: List[Any]
    progress: PublicInterviewProgress
    project: PublicInterviewProject
    project_id: StrictStr
    recording_ready: StrictBool = Field(description="`true` when an audio recording of the interview is available. Audio only: video is never exposed.")
    role_code: Optional[StrictStr]
    scoring_ready: StrictBool
    source: Optional[StrictStr] = Field(description="The calling system the candidate came from, as supplied when the interview was created; `null` when none was given.")
    started_at: Optional[StrictStr]
    status: StrictStr
    transcript_ready: StrictBool
    updated_at: StrictStr
    __properties: ClassVar[List[str]] = ["candidate_ref", "completed_at", "created_at", "display_name", "email", "exit_redirect_url", "external_id", "hosted_url", "id", "language", "livemode", "metadata", "progress", "project", "project_id", "recording_ready", "role_code", "scoring_ready", "source", "started_at", "status", "transcript_ready", "updated_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PublicInterview from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of progress
        if self.progress:
            _dict['progress'] = self.progress.to_dict()
        # override the default output from pydantic by calling `to_dict()` of project
        if self.project:
            _dict['project'] = self.project.to_dict()
        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completed_at'] = None

        # set to None if exit_redirect_url (nullable) is None
        # and model_fields_set contains the field
        if self.exit_redirect_url is None and "exit_redirect_url" in self.model_fields_set:
            _dict['exit_redirect_url'] = None

        # set to None if external_id (nullable) is None
        # and model_fields_set contains the field
        if self.external_id is None and "external_id" in self.model_fields_set:
            _dict['external_id'] = None

        # set to None if hosted_url (nullable) is None
        # and model_fields_set contains the field
        if self.hosted_url is None and "hosted_url" in self.model_fields_set:
            _dict['hosted_url'] = None

        # set to None if role_code (nullable) is None
        # and model_fields_set contains the field
        if self.role_code is None and "role_code" in self.model_fields_set:
            _dict['role_code'] = None

        # set to None if source (nullable) is None
        # and model_fields_set contains the field
        if self.source is None and "source" in self.model_fields_set:
            _dict['source'] = None

        # set to None if started_at (nullable) is None
        # and model_fields_set contains the field
        if self.started_at is None and "started_at" in self.model_fields_set:
            _dict['started_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PublicInterview from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "candidate_ref": obj.get("candidate_ref"),
            "completed_at": obj.get("completed_at"),
            "created_at": obj.get("created_at"),
            "display_name": obj.get("display_name"),
            "email": obj.get("email"),
            "exit_redirect_url": obj.get("exit_redirect_url"),
            "external_id": obj.get("external_id"),
            "hosted_url": obj.get("hosted_url"),
            "id": obj.get("id"),
            "language": obj.get("language"),
            "livemode": obj.get("livemode"),
            "metadata": obj.get("metadata"),
            "progress": PublicInterviewProgress.from_dict(obj["progress"]) if obj.get("progress") is not None else None,
            "project": PublicInterviewProject.from_dict(obj["project"]) if obj.get("project") is not None else None,
            "project_id": obj.get("project_id"),
            "recording_ready": obj.get("recording_ready"),
            "role_code": obj.get("role_code"),
            "scoring_ready": obj.get("scoring_ready"),
            "source": obj.get("source"),
            "started_at": obj.get("started_at"),
            "status": obj.get("status"),
            "transcript_ready": obj.get("transcript_ready"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


