/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.68.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The body of `POST /v1/exports`: what to export, in which format, and an optional
 * time window.
 * @export
 * @interface CreateExportRequest
 */
export interface CreateExportRequest {
    /**
     * 
     */
    format: CreateExportRequestFormatEnum;
    /**
     * 
     */
    from?: string | null;
    /**
     * 
     */
    includeAudio?: boolean;
    /**
     * 
     */
    includeScoring?: boolean;
    /**
     * 
     */
    includeTranscripts?: boolean;
    /**
     * 
     */
    scope: CreateExportRequestScopeEnum;
    /**
     * 
     */
    to?: string | null;
}


/**
 * @export
 */
export const CreateExportRequestFormatEnum = {
    Jsonl: 'jsonl',
    Csv: 'csv',
} as const;
export type CreateExportRequestFormatEnum = typeof CreateExportRequestFormatEnum[keyof typeof CreateExportRequestFormatEnum];

/**
 * @export
 */
export const CreateExportRequestScopeEnum = {
    All: 'all',
    Interviews: 'interviews',
} as const;
export type CreateExportRequestScopeEnum = typeof CreateExportRequestScopeEnum[keyof typeof CreateExportRequestScopeEnum];


/**
 * Check if a given object implements the CreateExportRequest interface.
 */
export function instanceOfCreateExportRequest(value: object): value is CreateExportRequest {
    if (!('format' in value) || value['format'] === undefined) return false;
    if (!('scope' in value) || value['scope'] === undefined) return false;
    return true;
}

export function CreateExportRequestFromJSON(json: any): CreateExportRequest {
    return CreateExportRequestFromJSONTyped(json, false);
}

export function CreateExportRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateExportRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'format': json['format'],
        'from': json['from'] === undefined ? undefined : json['from'] === null ? null : json['from'],
        'includeAudio': json['include_audio'] == null ? undefined : json['include_audio'],
        'includeScoring': json['include_scoring'] == null ? undefined : json['include_scoring'],
        'includeTranscripts': json['include_transcripts'] == null ? undefined : json['include_transcripts'],
        'scope': json['scope'],
        'to': json['to'] === undefined ? undefined : json['to'] === null ? null : json['to'],
    };
}

export function CreateExportRequestToJSON(json: any): CreateExportRequest {
    return CreateExportRequestToJSONTyped(json, false);
}

export function CreateExportRequestToJSONTyped(value?: CreateExportRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'format': value['format'],
        'from': value['from'],
        'include_audio': value['includeAudio'],
        'include_scoring': value['includeScoring'],
        'include_transcripts': value['includeTranscripts'],
        'scope': value['scope'],
        'to': value['to'],
    };
}

