/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateInterviewRequestCandidate } from './CreateInterviewRequestCandidate';
import {
    CreateInterviewRequestCandidateFromJSON,
    CreateInterviewRequestCandidateFromJSONTyped,
    CreateInterviewRequestCandidateToJSON,
    CreateInterviewRequestCandidateToJSONTyped,
} from './CreateInterviewRequestCandidate';

/**
 * The body of `POST /v1/interviews`: the candidate to enrol, the project to
 * enrol them on, and optional metadata and redirect URL.
 * @export
 * @interface CreateInterviewRequest
 */
export interface CreateInterviewRequest {
    /**
     * 
     */
    candidate: CreateInterviewRequestCandidate;
    /**
     * Must be an https URL of at most 2048 characters.
     */
    exitRedirectUrl?: string | null;
    /**
     * Free-form key/value pairs (≤ 20 keys, key ≤ 40 chars, value ≤ 500 chars).
     */
    metadata?: { [key: string]: string; } | null;
    /**
     * 
     */
    projectId: string;
}

/**
 * Check if a given object implements the CreateInterviewRequest interface.
 */
export function instanceOfCreateInterviewRequest(value: object): value is CreateInterviewRequest {
    if (!('candidate' in value) || value['candidate'] === undefined) return false;
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    return true;
}

export function CreateInterviewRequestFromJSON(json: any): CreateInterviewRequest {
    return CreateInterviewRequestFromJSONTyped(json, false);
}

export function CreateInterviewRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateInterviewRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'candidate': CreateInterviewRequestCandidateFromJSON(json['candidate']),
        'exitRedirectUrl': json['exit_redirect_url'] === undefined ? undefined : json['exit_redirect_url'] === null ? null : json['exit_redirect_url'],
        'metadata': json['metadata'] === undefined ? undefined : json['metadata'] === null ? null : json['metadata'],
        'projectId': json['project_id'],
    };
}

export function CreateInterviewRequestToJSON(json: any): CreateInterviewRequest {
    return CreateInterviewRequestToJSONTyped(json, false);
}

export function CreateInterviewRequestToJSONTyped(value?: CreateInterviewRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'candidate': CreateInterviewRequestCandidateToJSON(value['candidate']),
        'exit_redirect_url': value['exitRedirectUrl'],
        'metadata': value['metadata'],
        'project_id': value['projectId'],
    };
}

