/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InlineObject1
 */
export interface InlineObject1 {
    /**
     * A detailed description of each field that failed validation.
     */
    errors: { [key: string]: Array<string>; };
    /**
     * Errors overview.
     */
    message: string;
}

/**
 * Check if a given object implements the InlineObject1 interface.
 */
export function instanceOfInlineObject1(value: object): value is InlineObject1 {
    if (!('errors' in value) || value['errors'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function InlineObject1FromJSON(json: any): InlineObject1 {
    return InlineObject1FromJSONTyped(json, false);
}

export function InlineObject1FromJSONTyped(json: any, ignoreDiscriminator: boolean): InlineObject1 {
    if (json == null) {
        return json;
    }
    return {
        
        'errors': json['errors'],
        'message': json['message'],
    };
}

export function InlineObject1ToJSON(json: any): InlineObject1 {
    return InlineObject1ToJSONTyped(json, false);
}

export function InlineObject1ToJSONTyped(value?: InlineObject1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'errors': value['errors'],
        'message': value['message'],
    };
}

