/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicApiExportsIndex400ResponseErrorsInner } from './PublicApiExportsIndex400ResponseErrorsInner';
import {
    PublicApiExportsIndex400ResponseErrorsInnerFromJSON,
    PublicApiExportsIndex400ResponseErrorsInnerFromJSONTyped,
    PublicApiExportsIndex400ResponseErrorsInnerToJSON,
    PublicApiExportsIndex400ResponseErrorsInnerToJSONTyped,
} from './PublicApiExportsIndex400ResponseErrorsInner';

/**
 * 
 * @export
 * @interface PublicApiExportsIndex400Response
 */
export interface PublicApiExportsIndex400Response {
    /**
     * 
     */
    code: string;
    /**
     * 
     */
    detail?: string;
    /**
     * 
     */
    errors?: Array<PublicApiExportsIndex400ResponseErrorsInner>;
    /**
     * 
     */
    requestId: string;
    /**
     * 
     */
    status: number;
    /**
     * 
     */
    title: string;
    /**
     * 
     */
    type: string;
}

/**
 * Check if a given object implements the PublicApiExportsIndex400Response interface.
 */
export function instanceOfPublicApiExportsIndex400Response(value: object): value is PublicApiExportsIndex400Response {
    if (!('code' in value) || value['code'] === undefined) return false;
    if ((!('requestId' in (value as Record<string, any>)) && !('request_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['requestId'] === undefined && (value as Record<string, any>)['request_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function PublicApiExportsIndex400ResponseFromJSON(json: any): PublicApiExportsIndex400Response {
    return PublicApiExportsIndex400ResponseFromJSONTyped(json, false);
}

export function PublicApiExportsIndex400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicApiExportsIndex400Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'detail': json['detail'] == null ? undefined : json['detail'],
        'errors': json['errors'] == null ? undefined : ((json['errors'] as Array<any>).map(PublicApiExportsIndex400ResponseErrorsInnerFromJSON)),
        'requestId': json['request_id'],
        'status': json['status'],
        'title': json['title'],
        'type': json['type'],
    };
}

export function PublicApiExportsIndex400ResponseToJSON(json: any): PublicApiExportsIndex400Response {
    return PublicApiExportsIndex400ResponseToJSONTyped(json, false);
}

export function PublicApiExportsIndex400ResponseToJSONTyped(value?: PublicApiExportsIndex400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'detail': value['detail'],
        'errors': value['errors'] == null ? undefined : ((value['errors'] as Array<any>).map(PublicApiExportsIndex400ResponseErrorsInnerToJSON)),
        'request_id': value['requestId'],
        'status': value['status'],
        'title': value['title'],
        'type': value['type'],
    };
}

