/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicInterviewProjectFrameworkVersion } from './PublicInterviewProjectFrameworkVersion';
import {
    PublicInterviewProjectFrameworkVersionFromJSON,
    PublicInterviewProjectFrameworkVersionFromJSONTyped,
    PublicInterviewProjectFrameworkVersionToJSON,
    PublicInterviewProjectFrameworkVersionToJSONTyped,
} from './PublicInterviewProjectFrameworkVersion';

/**
 * 
 * @export
 * @interface PublicProject
 */
export interface PublicProject {
    /**
     * 
     */
    assessmentType: string;
    /**
     * 
     */
    avatarDisplayName: string;
    /**
     * 
     */
    competencies: Array<any>;
    /**
     * 
     */
    createdAt: string;
    /**
     * 
     */
    exitRedirectUrl: string | null;
    /**
     * 
     */
    frameworkVersion: PublicInterviewProjectFrameworkVersion;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    language: string;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    nudgeMinChars: number | null;
    /**
     * 
     */
    pauseEveryNCompetencies: number | null;
    /**
     * 
     */
    roleCode: string | null;
    /**
     * 
     */
    slug: string;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    updatedAt: string;
}

/**
 * Check if a given object implements the PublicProject interface.
 */
export function instanceOfPublicProject(value: object): value is PublicProject {
    if ((!('assessmentType' in (value as Record<string, any>)) && !('assessment_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['assessmentType'] === undefined && (value as Record<string, any>)['assessment_type'] === undefined)) return false;
    if ((!('avatarDisplayName' in (value as Record<string, any>)) && !('avatar_display_name' in (value as Record<string, any>))) || ((value as Record<string, any>)['avatarDisplayName'] === undefined && (value as Record<string, any>)['avatar_display_name'] === undefined)) return false;
    if (!('competencies' in value) || value['competencies'] === undefined) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('exitRedirectUrl' in (value as Record<string, any>)) && !('exit_redirect_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['exitRedirectUrl'] === undefined && (value as Record<string, any>)['exit_redirect_url'] === undefined)) return false;
    if ((!('frameworkVersion' in (value as Record<string, any>)) && !('framework_version' in (value as Record<string, any>))) || ((value as Record<string, any>)['frameworkVersion'] === undefined && (value as Record<string, any>)['framework_version'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if ((!('nudgeMinChars' in (value as Record<string, any>)) && !('nudge_min_chars' in (value as Record<string, any>))) || ((value as Record<string, any>)['nudgeMinChars'] === undefined && (value as Record<string, any>)['nudge_min_chars'] === undefined)) return false;
    if ((!('pauseEveryNCompetencies' in (value as Record<string, any>)) && !('pause_every_n_competencies' in (value as Record<string, any>))) || ((value as Record<string, any>)['pauseEveryNCompetencies'] === undefined && (value as Record<string, any>)['pause_every_n_competencies'] === undefined)) return false;
    if ((!('roleCode' in (value as Record<string, any>)) && !('role_code' in (value as Record<string, any>))) || ((value as Record<string, any>)['roleCode'] === undefined && (value as Record<string, any>)['role_code'] === undefined)) return false;
    if (!('slug' in value) || value['slug'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('updatedAt' in (value as Record<string, any>)) && !('updated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['updatedAt'] === undefined && (value as Record<string, any>)['updated_at'] === undefined)) return false;
    return true;
}

export function PublicProjectFromJSON(json: any): PublicProject {
    return PublicProjectFromJSONTyped(json, false);
}

export function PublicProjectFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicProject {
    if (json == null) {
        return json;
    }
    return {
        
        'assessmentType': json['assessment_type'],
        'avatarDisplayName': json['avatar_display_name'],
        'competencies': json['competencies'],
        'createdAt': json['created_at'],
        'exitRedirectUrl': json['exit_redirect_url'],
        'frameworkVersion': PublicInterviewProjectFrameworkVersionFromJSON(json['framework_version']),
        'id': json['id'],
        'language': json['language'],
        'name': json['name'],
        'nudgeMinChars': json['nudge_min_chars'],
        'pauseEveryNCompetencies': json['pause_every_n_competencies'],
        'roleCode': json['role_code'],
        'slug': json['slug'],
        'status': json['status'],
        'updatedAt': json['updated_at'],
    };
}

export function PublicProjectToJSON(json: any): PublicProject {
    return PublicProjectToJSONTyped(json, false);
}

export function PublicProjectToJSONTyped(value?: PublicProject | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'assessment_type': value['assessmentType'],
        'avatar_display_name': value['avatarDisplayName'],
        'competencies': value['competencies'],
        'created_at': value['createdAt'],
        'exit_redirect_url': value['exitRedirectUrl'],
        'framework_version': PublicInterviewProjectFrameworkVersionToJSON(value['frameworkVersion']),
        'id': value['id'],
        'language': value['language'],
        'name': value['name'],
        'nudge_min_chars': value['nudgeMinChars'],
        'pause_every_n_competencies': value['pauseEveryNCompetencies'],
        'role_code': value['roleCode'],
        'slug': value['slug'],
        'status': value['status'],
        'updated_at': value['updatedAt'],
    };
}

