/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicApiInterviewsStore409ResponseAnyOf1
 */
export interface PublicApiInterviewsStore409ResponseAnyOf1 {
    /**
     * 
     */
    code: PublicApiInterviewsStore409ResponseAnyOf1CodeEnum;
    /**
     * 
     */
    detail: PublicApiInterviewsStore409ResponseAnyOf1DetailEnum;
    /**
     * 
     */
    errors: string | null;
    /**
     * 
     */
    requestId: string;
    /**
     * 
     */
    status: PublicApiInterviewsStore409ResponseAnyOf1StatusEnum;
    /**
     * 
     */
    title: PublicApiInterviewsStore409ResponseAnyOf1TitleEnum;
    /**
     * 
     */
    type: string;
}


/**
 * @export
 */
export const PublicApiInterviewsStore409ResponseAnyOf1CodeEnum = {
    DuplicateEnrolment: 'duplicate_enrolment',
} as const;
export type PublicApiInterviewsStore409ResponseAnyOf1CodeEnum = typeof PublicApiInterviewsStore409ResponseAnyOf1CodeEnum[keyof typeof PublicApiInterviewsStore409ResponseAnyOf1CodeEnum];

/**
 * @export
 */
export const PublicApiInterviewsStore409ResponseAnyOf1DetailEnum = {
    CandidateCandidateRefIsAlreadyEnrolledInThisProject: 'candidate.candidate_ref is already enrolled in this project.',
} as const;
export type PublicApiInterviewsStore409ResponseAnyOf1DetailEnum = typeof PublicApiInterviewsStore409ResponseAnyOf1DetailEnum[keyof typeof PublicApiInterviewsStore409ResponseAnyOf1DetailEnum];

/**
 * @export
 */
export const PublicApiInterviewsStore409ResponseAnyOf1StatusEnum = {
    NUMBER_409: 409,
} as const;
export type PublicApiInterviewsStore409ResponseAnyOf1StatusEnum = typeof PublicApiInterviewsStore409ResponseAnyOf1StatusEnum[keyof typeof PublicApiInterviewsStore409ResponseAnyOf1StatusEnum];

/**
 * @export
 */
export const PublicApiInterviewsStore409ResponseAnyOf1TitleEnum = {
    DuplicateEnrolment: 'Duplicate enrolment',
} as const;
export type PublicApiInterviewsStore409ResponseAnyOf1TitleEnum = typeof PublicApiInterviewsStore409ResponseAnyOf1TitleEnum[keyof typeof PublicApiInterviewsStore409ResponseAnyOf1TitleEnum];


/**
 * Check if a given object implements the PublicApiInterviewsStore409ResponseAnyOf1 interface.
 */
export function instanceOfPublicApiInterviewsStore409ResponseAnyOf1(value: object): value is PublicApiInterviewsStore409ResponseAnyOf1 {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (value['code'] !== 'duplicate_enrolment') return false;
    
    if (!('detail' in value) || value['detail'] === undefined) return false;
    if (value['detail'] !== 'candidate.candidate_ref is already enrolled in this project.') return false;
    
    if (!('errors' in value) || value['errors'] === undefined) return false;
    if ((!('requestId' in (value as Record<string, any>)) && !('request_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['requestId'] === undefined && (value as Record<string, any>)['request_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    
    if (value['status'] !== 409) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (value['title'] !== 'Duplicate enrolment') return false;
    
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function PublicApiInterviewsStore409ResponseAnyOf1FromJSON(json: any): PublicApiInterviewsStore409ResponseAnyOf1 {
    return PublicApiInterviewsStore409ResponseAnyOf1FromJSONTyped(json, false);
}

export function PublicApiInterviewsStore409ResponseAnyOf1FromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicApiInterviewsStore409ResponseAnyOf1 {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'detail': json['detail'],
        'errors': json['errors'],
        'requestId': json['request_id'],
        'status': json['status'],
        'title': json['title'],
        'type': json['type'],
    };
}

export function PublicApiInterviewsStore409ResponseAnyOf1ToJSON(json: any): PublicApiInterviewsStore409ResponseAnyOf1 {
    return PublicApiInterviewsStore409ResponseAnyOf1ToJSONTyped(json, false);
}

export function PublicApiInterviewsStore409ResponseAnyOf1ToJSONTyped(value?: PublicApiInterviewsStore409ResponseAnyOf1 | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'detail': value['detail'],
        'errors': value['errors'],
        'request_id': value['requestId'],
        'status': value['status'],
        'title': value['title'],
        'type': value['type'],
    };
}

