/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicApiUsageShow200ResponseInterviews
 */
export interface PublicApiUsageShow200ResponseInterviews {
    /**
     * 
     */
    completed: number;
    /**
     * 
     */
    error: number;
    /**
     * 
     */
    inProgress: number;
    /**
     * 
     */
    pending: number;
    /**
     * 
     */
    underEvaluation: number;
}

/**
 * Check if a given object implements the PublicApiUsageShow200ResponseInterviews interface.
 */
export function instanceOfPublicApiUsageShow200ResponseInterviews(value: object): value is PublicApiUsageShow200ResponseInterviews {
    if (!('completed' in value) || value['completed'] === undefined) return false;
    if (!('error' in value) || value['error'] === undefined) return false;
    if ((!('inProgress' in (value as Record<string, any>)) && !('in_progress' in (value as Record<string, any>))) || ((value as Record<string, any>)['inProgress'] === undefined && (value as Record<string, any>)['in_progress'] === undefined)) return false;
    if (!('pending' in value) || value['pending'] === undefined) return false;
    if ((!('underEvaluation' in (value as Record<string, any>)) && !('under_evaluation' in (value as Record<string, any>))) || ((value as Record<string, any>)['underEvaluation'] === undefined && (value as Record<string, any>)['under_evaluation'] === undefined)) return false;
    return true;
}

export function PublicApiUsageShow200ResponseInterviewsFromJSON(json: any): PublicApiUsageShow200ResponseInterviews {
    return PublicApiUsageShow200ResponseInterviewsFromJSONTyped(json, false);
}

export function PublicApiUsageShow200ResponseInterviewsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicApiUsageShow200ResponseInterviews {
    if (json == null) {
        return json;
    }
    return {
        
        'completed': json['completed'],
        'error': json['error'],
        'inProgress': json['in_progress'],
        'pending': json['pending'],
        'underEvaluation': json['under_evaluation'],
    };
}

export function PublicApiUsageShow200ResponseInterviewsToJSON(json: any): PublicApiUsageShow200ResponseInterviews {
    return PublicApiUsageShow200ResponseInterviewsToJSONTyped(json, false);
}

export function PublicApiUsageShow200ResponseInterviewsToJSONTyped(value?: PublicApiUsageShow200ResponseInterviews | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'completed': value['completed'],
        'error': value['error'],
        'in_progress': value['inProgress'],
        'pending': value['pending'],
        'under_evaluation': value['underEvaluation'],
    };
}

