/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.68.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicOrganization
 */
export interface PublicOrganization {
    /**
     * 
     */
    allowedDomains: Array<any>;
    /**
     * 
     */
    createdAt: string;
    /**
     * 
     */
    id: string;
    /**
     * The mode of the API key making the request, not a property of the organization: the same organization answers `live` through a live key and `test` through a test key.
     */
    mode: string;
    /**
     * 
     */
    name: string;
}

/**
 * Check if a given object implements the PublicOrganization interface.
 */
export function instanceOfPublicOrganization(value: object): value is PublicOrganization {
    if ((!('allowedDomains' in (value as Record<string, any>)) && !('allowed_domains' in (value as Record<string, any>))) || ((value as Record<string, any>)['allowedDomains'] === undefined && (value as Record<string, any>)['allowed_domains'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('mode' in value) || value['mode'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function PublicOrganizationFromJSON(json: any): PublicOrganization {
    return PublicOrganizationFromJSONTyped(json, false);
}

export function PublicOrganizationFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicOrganization {
    if (json == null) {
        return json;
    }
    return {
        
        'allowedDomains': json['allowed_domains'],
        'createdAt': json['created_at'],
        'id': json['id'],
        'mode': json['mode'],
        'name': json['name'],
    };
}

export function PublicOrganizationToJSON(json: any): PublicOrganization {
    return PublicOrganizationToJSONTyped(json, false);
}

export function PublicOrganizationToJSONTyped(value?: PublicOrganization | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowed_domains': value['allowedDomains'],
        'created_at': value['createdAt'],
        'id': value['id'],
        'mode': value['mode'],
        'name': value['name'],
    };
}

