/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicInterview } from './PublicInterview';
import {
    PublicInterviewFromJSON,
    PublicInterviewFromJSONTyped,
    PublicInterviewToJSON,
    PublicInterviewToJSONTyped,
} from './PublicInterview';

/**
 * 
 * @export
 * @interface PublicApiInterviewsIndex200Response
 */
export interface PublicApiInterviewsIndex200Response {
    /**
     * 
     */
    data: Array<PublicInterview>;
    /**
     * 
     */
    hasMore: boolean;
    /**
     * 
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the PublicApiInterviewsIndex200Response interface.
 */
export function instanceOfPublicApiInterviewsIndex200Response(value: object): value is PublicApiInterviewsIndex200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if ((!('hasMore' in (value as Record<string, any>)) && !('has_more' in (value as Record<string, any>))) || ((value as Record<string, any>)['hasMore'] === undefined && (value as Record<string, any>)['has_more'] === undefined)) return false;
    if ((!('nextCursor' in (value as Record<string, any>)) && !('next_cursor' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextCursor'] === undefined && (value as Record<string, any>)['next_cursor'] === undefined)) return false;
    return true;
}

export function PublicApiInterviewsIndex200ResponseFromJSON(json: any): PublicApiInterviewsIndex200Response {
    return PublicApiInterviewsIndex200ResponseFromJSONTyped(json, false);
}

export function PublicApiInterviewsIndex200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicApiInterviewsIndex200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(PublicInterviewFromJSON)),
        'hasMore': json['has_more'],
        'nextCursor': json['next_cursor'],
    };
}

export function PublicApiInterviewsIndex200ResponseToJSON(json: any): PublicApiInterviewsIndex200Response {
    return PublicApiInterviewsIndex200ResponseToJSONTyped(json, false);
}

export function PublicApiInterviewsIndex200ResponseToJSONTyped(value?: PublicApiInterviewsIndex200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(PublicInterviewToJSON)),
        'has_more': value['hasMore'],
        'next_cursor': value['nextCursor'],
    };
}

