/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.68.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicProject } from './PublicProject';
import {
    PublicProjectFromJSON,
    PublicProjectFromJSONTyped,
    PublicProjectToJSON,
    PublicProjectToJSONTyped,
} from './PublicProject';

/**
 * 
 * @export
 * @interface PublicApiProjectsIndex200Response
 */
export interface PublicApiProjectsIndex200Response {
    /**
     * 
     */
    data: Array<PublicProject>;
    /**
     * 
     */
    hasMore: boolean;
    /**
     * 
     */
    nextCursor: string | null;
}

/**
 * Check if a given object implements the PublicApiProjectsIndex200Response interface.
 */
export function instanceOfPublicApiProjectsIndex200Response(value: object): value is PublicApiProjectsIndex200Response {
    if (!('data' in value) || value['data'] === undefined) return false;
    if ((!('hasMore' in (value as Record<string, any>)) && !('has_more' in (value as Record<string, any>))) || ((value as Record<string, any>)['hasMore'] === undefined && (value as Record<string, any>)['has_more'] === undefined)) return false;
    if ((!('nextCursor' in (value as Record<string, any>)) && !('next_cursor' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextCursor'] === undefined && (value as Record<string, any>)['next_cursor'] === undefined)) return false;
    return true;
}

export function PublicApiProjectsIndex200ResponseFromJSON(json: any): PublicApiProjectsIndex200Response {
    return PublicApiProjectsIndex200ResponseFromJSONTyped(json, false);
}

export function PublicApiProjectsIndex200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicApiProjectsIndex200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(PublicProjectFromJSON)),
        'hasMore': json['has_more'],
        'nextCursor': json['next_cursor'],
    };
}

export function PublicApiProjectsIndex200ResponseToJSON(json: any): PublicApiProjectsIndex200Response {
    return PublicApiProjectsIndex200ResponseToJSONTyped(json, false);
}

export function PublicApiProjectsIndex200ResponseToJSONTyped(value?: PublicApiProjectsIndex200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': ((value['data'] as Array<any>).map(PublicProjectToJSON)),
        'has_more': value['hasMore'],
        'next_cursor': value['nextCursor'],
    };
}

