/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicApiWebhooksDeliveriesIndex200ResponseDataInner
 */
export interface PublicApiWebhooksDeliveriesIndex200ResponseDataInner {
    /**
     * 
     */
    attemptCount: number;
    /**
     * 
     */
    candidateRef: string;
    /**
     * 
     */
    createdAt: string;
    /**
     * 
     */
    deliveredAt: string | null;
    /**
     * 
     */
    eventType: string;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    interviewId: string;
    /**
     * 
     */
    lastAttemptAt: string | null;
    /**
     * 
     */
    lastResponseStatus: number | null;
    /**
     * 
     */
    maxAttempts: number;
    /**
     * 
     */
    nextAttemptAt: string | null;
    /**
     * 
     */
    payloadVersion: string;
    /**
     * 
     */
    projectId: string;
    /**
     * 
     */
    status: string;
    /**
     * 
     */
    targetUrl: string | null;
}

/**
 * Check if a given object implements the PublicApiWebhooksDeliveriesIndex200ResponseDataInner interface.
 */
export function instanceOfPublicApiWebhooksDeliveriesIndex200ResponseDataInner(value: object): value is PublicApiWebhooksDeliveriesIndex200ResponseDataInner {
    if ((!('attemptCount' in (value as Record<string, any>)) && !('attempt_count' in (value as Record<string, any>))) || ((value as Record<string, any>)['attemptCount'] === undefined && (value as Record<string, any>)['attempt_count'] === undefined)) return false;
    if ((!('candidateRef' in (value as Record<string, any>)) && !('candidate_ref' in (value as Record<string, any>))) || ((value as Record<string, any>)['candidateRef'] === undefined && (value as Record<string, any>)['candidate_ref'] === undefined)) return false;
    if ((!('createdAt' in (value as Record<string, any>)) && !('created_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['createdAt'] === undefined && (value as Record<string, any>)['created_at'] === undefined)) return false;
    if ((!('deliveredAt' in (value as Record<string, any>)) && !('delivered_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['deliveredAt'] === undefined && (value as Record<string, any>)['delivered_at'] === undefined)) return false;
    if ((!('eventType' in (value as Record<string, any>)) && !('event_type' in (value as Record<string, any>))) || ((value as Record<string, any>)['eventType'] === undefined && (value as Record<string, any>)['event_type'] === undefined)) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('interviewId' in (value as Record<string, any>)) && !('interview_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['interviewId'] === undefined && (value as Record<string, any>)['interview_id'] === undefined)) return false;
    if ((!('lastAttemptAt' in (value as Record<string, any>)) && !('last_attempt_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['lastAttemptAt'] === undefined && (value as Record<string, any>)['last_attempt_at'] === undefined)) return false;
    if ((!('lastResponseStatus' in (value as Record<string, any>)) && !('last_response_status' in (value as Record<string, any>))) || ((value as Record<string, any>)['lastResponseStatus'] === undefined && (value as Record<string, any>)['last_response_status'] === undefined)) return false;
    if ((!('maxAttempts' in (value as Record<string, any>)) && !('max_attempts' in (value as Record<string, any>))) || ((value as Record<string, any>)['maxAttempts'] === undefined && (value as Record<string, any>)['max_attempts'] === undefined)) return false;
    if ((!('nextAttemptAt' in (value as Record<string, any>)) && !('next_attempt_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['nextAttemptAt'] === undefined && (value as Record<string, any>)['next_attempt_at'] === undefined)) return false;
    if ((!('payloadVersion' in (value as Record<string, any>)) && !('payload_version' in (value as Record<string, any>))) || ((value as Record<string, any>)['payloadVersion'] === undefined && (value as Record<string, any>)['payload_version'] === undefined)) return false;
    if ((!('projectId' in (value as Record<string, any>)) && !('project_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['projectId'] === undefined && (value as Record<string, any>)['project_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if ((!('targetUrl' in (value as Record<string, any>)) && !('target_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['targetUrl'] === undefined && (value as Record<string, any>)['target_url'] === undefined)) return false;
    return true;
}

export function PublicApiWebhooksDeliveriesIndex200ResponseDataInnerFromJSON(json: any): PublicApiWebhooksDeliveriesIndex200ResponseDataInner {
    return PublicApiWebhooksDeliveriesIndex200ResponseDataInnerFromJSONTyped(json, false);
}

export function PublicApiWebhooksDeliveriesIndex200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicApiWebhooksDeliveriesIndex200ResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'attemptCount': json['attempt_count'],
        'candidateRef': json['candidate_ref'],
        'createdAt': json['created_at'],
        'deliveredAt': json['delivered_at'],
        'eventType': json['event_type'],
        'id': json['id'],
        'interviewId': json['interview_id'],
        'lastAttemptAt': json['last_attempt_at'],
        'lastResponseStatus': json['last_response_status'],
        'maxAttempts': json['max_attempts'],
        'nextAttemptAt': json['next_attempt_at'],
        'payloadVersion': json['payload_version'],
        'projectId': json['project_id'],
        'status': json['status'],
        'targetUrl': json['target_url'],
    };
}

export function PublicApiWebhooksDeliveriesIndex200ResponseDataInnerToJSON(json: any): PublicApiWebhooksDeliveriesIndex200ResponseDataInner {
    return PublicApiWebhooksDeliveriesIndex200ResponseDataInnerToJSONTyped(json, false);
}

export function PublicApiWebhooksDeliveriesIndex200ResponseDataInnerToJSONTyped(value?: PublicApiWebhooksDeliveriesIndex200ResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'attempt_count': value['attemptCount'],
        'candidate_ref': value['candidateRef'],
        'created_at': value['createdAt'],
        'delivered_at': value['deliveredAt'],
        'event_type': value['eventType'],
        'id': value['id'],
        'interview_id': value['interviewId'],
        'last_attempt_at': value['lastAttemptAt'],
        'last_response_status': value['lastResponseStatus'],
        'max_attempts': value['maxAttempts'],
        'next_attempt_at': value['nextAttemptAt'],
        'payload_version': value['payloadVersion'],
        'project_id': value['projectId'],
        'status': value['status'],
        'target_url': value['targetUrl'],
    };
}

