/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.68.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicInterviewProjectFrameworkVersion
 */
export interface PublicInterviewProjectFrameworkVersion {
    /**
     * 
     */
    label: string | null;
    /**
     * The version of the framework the project is pinned to.
     */
    version: string;
}

/**
 * Check if a given object implements the PublicInterviewProjectFrameworkVersion interface.
 */
export function instanceOfPublicInterviewProjectFrameworkVersion(value: object): value is PublicInterviewProjectFrameworkVersion {
    if (!('label' in value) || value['label'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    return true;
}

export function PublicInterviewProjectFrameworkVersionFromJSON(json: any): PublicInterviewProjectFrameworkVersion {
    return PublicInterviewProjectFrameworkVersionFromJSONTyped(json, false);
}

export function PublicInterviewProjectFrameworkVersionFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicInterviewProjectFrameworkVersion {
    if (json == null) {
        return json;
    }
    return {
        
        'label': json['label'],
        'version': json['version'],
    };
}

export function PublicInterviewProjectFrameworkVersionToJSON(json: any): PublicInterviewProjectFrameworkVersion {
    return PublicInterviewProjectFrameworkVersionToJSONTyped(json, false);
}

export function PublicInterviewProjectFrameworkVersionToJSONTyped(value?: PublicInterviewProjectFrameworkVersion | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'label': value['label'],
        'version': value['version'],
    };
}

