/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicApiInterviewsTranscript200ResponseTurnsInner
 */
export interface PublicApiInterviewsTranscript200ResponseTurnsInner {
    /**
     * 
     */
    competencyCode: string;
    /**
     * 
     */
    index: number;
    /**
     * 
     */
    questionIndex: number;
    /**
     * 
     */
    speaker: string;
    /**
     * 
     */
    text: string;
    /**
     * 
     */
    ts: string;
}

/**
 * Check if a given object implements the PublicApiInterviewsTranscript200ResponseTurnsInner interface.
 */
export function instanceOfPublicApiInterviewsTranscript200ResponseTurnsInner(value: object): value is PublicApiInterviewsTranscript200ResponseTurnsInner {
    if ((!('competencyCode' in (value as Record<string, any>)) && !('competency_code' in (value as Record<string, any>))) || ((value as Record<string, any>)['competencyCode'] === undefined && (value as Record<string, any>)['competency_code'] === undefined)) return false;
    if (!('index' in value) || value['index'] === undefined) return false;
    if ((!('questionIndex' in (value as Record<string, any>)) && !('question_index' in (value as Record<string, any>))) || ((value as Record<string, any>)['questionIndex'] === undefined && (value as Record<string, any>)['question_index'] === undefined)) return false;
    if (!('speaker' in value) || value['speaker'] === undefined) return false;
    if (!('text' in value) || value['text'] === undefined) return false;
    if (!('ts' in value) || value['ts'] === undefined) return false;
    return true;
}

export function PublicApiInterviewsTranscript200ResponseTurnsInnerFromJSON(json: any): PublicApiInterviewsTranscript200ResponseTurnsInner {
    return PublicApiInterviewsTranscript200ResponseTurnsInnerFromJSONTyped(json, false);
}

export function PublicApiInterviewsTranscript200ResponseTurnsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicApiInterviewsTranscript200ResponseTurnsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'competencyCode': json['competency_code'],
        'index': json['index'],
        'questionIndex': json['question_index'],
        'speaker': json['speaker'],
        'text': json['text'],
        'ts': json['ts'],
    };
}

export function PublicApiInterviewsTranscript200ResponseTurnsInnerToJSON(json: any): PublicApiInterviewsTranscript200ResponseTurnsInner {
    return PublicApiInterviewsTranscript200ResponseTurnsInnerToJSONTyped(json, false);
}

export function PublicApiInterviewsTranscript200ResponseTurnsInnerToJSONTyped(value?: PublicApiInterviewsTranscript200ResponseTurnsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'competency_code': value['competencyCode'],
        'index': value['index'],
        'question_index': value['questionIndex'],
        'speaker': value['speaker'],
        'text': value['text'],
        'ts': value['ts'],
    };
}

