/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.68.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicInterviewProgressAnyOfInner } from './PublicInterviewProgressAnyOfInner';
import {
    PublicInterviewProgressAnyOfInnerFromJSON,
    PublicInterviewProgressAnyOfInnerFromJSONTyped,
    PublicInterviewProgressAnyOfInnerToJSON,
    PublicInterviewProgressAnyOfInnerToJSONTyped,
} from './PublicInterviewProgressAnyOfInner';

/**
 * 
 * @export
 * @interface PublicInterviewProgress
 */
export interface PublicInterviewProgress {
}

/**
 * Check if a given object implements the PublicInterviewProgress interface.
 */
export function instanceOfPublicInterviewProgress(value: object): value is PublicInterviewProgress {
    return true;
}

export function PublicInterviewProgressFromJSON(json: any): PublicInterviewProgress {
    return PublicInterviewProgressFromJSONTyped(json, false);
}

export function PublicInterviewProgressFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicInterviewProgress {
    return json;
}

export function PublicInterviewProgressToJSON(json: any): PublicInterviewProgress {
    return PublicInterviewProgressToJSONTyped(json, false);
}

export function PublicInterviewProgressToJSONTyped(value?: PublicInterviewProgress | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

