/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicApiInterviewsScoring200ResponseCompetenciesValue } from './PublicApiInterviewsScoring200ResponseCompetenciesValue';
import {
    PublicApiInterviewsScoring200ResponseCompetenciesValueFromJSON,
    PublicApiInterviewsScoring200ResponseCompetenciesValueFromJSONTyped,
    PublicApiInterviewsScoring200ResponseCompetenciesValueToJSON,
    PublicApiInterviewsScoring200ResponseCompetenciesValueToJSONTyped,
} from './PublicApiInterviewsScoring200ResponseCompetenciesValue';

/**
 * 
 * @export
 * @interface PublicApiInterviewsScoring200Response
 */
export interface PublicApiInterviewsScoring200Response {
    /**
     * 
     */
    competencies: { [key: string]: PublicApiInterviewsScoring200ResponseCompetenciesValue; };
    /**
     * 
     */
    evaluatedAt: string;
    /**
     * 
     */
    frameworkVersion: string;
    /**
     * 
     */
    interviewId: string;
    /**
     * 
     */
    modelVersion: string;
    /**
     * 
     */
    promptVersion: string;
    /**
     * 
     */
    status: string;
}

/**
 * Check if a given object implements the PublicApiInterviewsScoring200Response interface.
 */
export function instanceOfPublicApiInterviewsScoring200Response(value: object): value is PublicApiInterviewsScoring200Response {
    if (!('competencies' in value) || value['competencies'] === undefined) return false;
    if ((!('evaluatedAt' in (value as Record<string, any>)) && !('evaluated_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['evaluatedAt'] === undefined && (value as Record<string, any>)['evaluated_at'] === undefined)) return false;
    if ((!('frameworkVersion' in (value as Record<string, any>)) && !('framework_version' in (value as Record<string, any>))) || ((value as Record<string, any>)['frameworkVersion'] === undefined && (value as Record<string, any>)['framework_version'] === undefined)) return false;
    if ((!('interviewId' in (value as Record<string, any>)) && !('interview_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['interviewId'] === undefined && (value as Record<string, any>)['interview_id'] === undefined)) return false;
    if ((!('modelVersion' in (value as Record<string, any>)) && !('model_version' in (value as Record<string, any>))) || ((value as Record<string, any>)['modelVersion'] === undefined && (value as Record<string, any>)['model_version'] === undefined)) return false;
    if ((!('promptVersion' in (value as Record<string, any>)) && !('prompt_version' in (value as Record<string, any>))) || ((value as Record<string, any>)['promptVersion'] === undefined && (value as Record<string, any>)['prompt_version'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function PublicApiInterviewsScoring200ResponseFromJSON(json: any): PublicApiInterviewsScoring200Response {
    return PublicApiInterviewsScoring200ResponseFromJSONTyped(json, false);
}

export function PublicApiInterviewsScoring200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicApiInterviewsScoring200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'competencies': (mapValues(json['competencies'], PublicApiInterviewsScoring200ResponseCompetenciesValueFromJSON)),
        'evaluatedAt': json['evaluated_at'],
        'frameworkVersion': json['framework_version'],
        'interviewId': json['interview_id'],
        'modelVersion': json['model_version'],
        'promptVersion': json['prompt_version'],
        'status': json['status'],
    };
}

export function PublicApiInterviewsScoring200ResponseToJSON(json: any): PublicApiInterviewsScoring200Response {
    return PublicApiInterviewsScoring200ResponseToJSONTyped(json, false);
}

export function PublicApiInterviewsScoring200ResponseToJSONTyped(value?: PublicApiInterviewsScoring200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'competencies': (mapValues(value['competencies'], PublicApiInterviewsScoring200ResponseCompetenciesValueToJSON)),
        'evaluated_at': value['evaluatedAt'],
        'framework_version': value['frameworkVersion'],
        'interview_id': value['interviewId'],
        'model_version': value['modelVersion'],
        'prompt_version': value['promptVersion'],
        'status': value['status'],
    };
}

