/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicApiInterviewsScoring200ResponseCompetenciesValueBehaviorsInner } from './PublicApiInterviewsScoring200ResponseCompetenciesValueBehaviorsInner';
import {
    PublicApiInterviewsScoring200ResponseCompetenciesValueBehaviorsInnerFromJSON,
    PublicApiInterviewsScoring200ResponseCompetenciesValueBehaviorsInnerFromJSONTyped,
    PublicApiInterviewsScoring200ResponseCompetenciesValueBehaviorsInnerToJSON,
    PublicApiInterviewsScoring200ResponseCompetenciesValueBehaviorsInnerToJSONTyped,
} from './PublicApiInterviewsScoring200ResponseCompetenciesValueBehaviorsInner';

/**
 * 
 * @export
 * @interface PublicApiInterviewsScoring200ResponseCompetenciesValue
 */
export interface PublicApiInterviewsScoring200ResponseCompetenciesValue {
    /**
     * 
     */
    behaviors: Array<PublicApiInterviewsScoring200ResponseCompetenciesValueBehaviorsInner>;
    /**
     * 
     */
    reliability: number;
    /**
     * 
     */
    score: number | null;
    /**
     * 
     */
    unscorableReason: string | null;
}

/**
 * Check if a given object implements the PublicApiInterviewsScoring200ResponseCompetenciesValue interface.
 */
export function instanceOfPublicApiInterviewsScoring200ResponseCompetenciesValue(value: object): value is PublicApiInterviewsScoring200ResponseCompetenciesValue {
    if (!('behaviors' in value) || value['behaviors'] === undefined) return false;
    if (!('reliability' in value) || value['reliability'] === undefined) return false;
    if (!('score' in value) || value['score'] === undefined) return false;
    if ((!('unscorableReason' in (value as Record<string, any>)) && !('unscorable_reason' in (value as Record<string, any>))) || ((value as Record<string, any>)['unscorableReason'] === undefined && (value as Record<string, any>)['unscorable_reason'] === undefined)) return false;
    return true;
}

export function PublicApiInterviewsScoring200ResponseCompetenciesValueFromJSON(json: any): PublicApiInterviewsScoring200ResponseCompetenciesValue {
    return PublicApiInterviewsScoring200ResponseCompetenciesValueFromJSONTyped(json, false);
}

export function PublicApiInterviewsScoring200ResponseCompetenciesValueFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicApiInterviewsScoring200ResponseCompetenciesValue {
    if (json == null) {
        return json;
    }
    return {
        
        'behaviors': ((json['behaviors'] as Array<any>).map(PublicApiInterviewsScoring200ResponseCompetenciesValueBehaviorsInnerFromJSON)),
        'reliability': json['reliability'],
        'score': json['score'],
        'unscorableReason': json['unscorable_reason'],
    };
}

export function PublicApiInterviewsScoring200ResponseCompetenciesValueToJSON(json: any): PublicApiInterviewsScoring200ResponseCompetenciesValue {
    return PublicApiInterviewsScoring200ResponseCompetenciesValueToJSONTyped(json, false);
}

export function PublicApiInterviewsScoring200ResponseCompetenciesValueToJSONTyped(value?: PublicApiInterviewsScoring200ResponseCompetenciesValue | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'behaviors': ((value['behaviors'] as Array<any>).map(PublicApiInterviewsScoring200ResponseCompetenciesValueBehaviorsInnerToJSON)),
        'reliability': value['reliability'],
        'score': value['score'],
        'unscorable_reason': value['unscorableReason'],
    };
}

