/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicApiInterviewsTranscript200ResponseTurnsInner } from './PublicApiInterviewsTranscript200ResponseTurnsInner';
import {
    PublicApiInterviewsTranscript200ResponseTurnsInnerFromJSON,
    PublicApiInterviewsTranscript200ResponseTurnsInnerFromJSONTyped,
    PublicApiInterviewsTranscript200ResponseTurnsInnerToJSON,
    PublicApiInterviewsTranscript200ResponseTurnsInnerToJSONTyped,
} from './PublicApiInterviewsTranscript200ResponseTurnsInner';

/**
 * 
 * @export
 * @interface PublicApiInterviewsTranscript200Response
 */
export interface PublicApiInterviewsTranscript200Response {
    /**
     * 
     */
    interviewId: string;
    /**
     * 
     */
    language: string;
    /**
     * 
     */
    turns: Array<PublicApiInterviewsTranscript200ResponseTurnsInner>;
}

/**
 * Check if a given object implements the PublicApiInterviewsTranscript200Response interface.
 */
export function instanceOfPublicApiInterviewsTranscript200Response(value: object): value is PublicApiInterviewsTranscript200Response {
    if ((!('interviewId' in (value as Record<string, any>)) && !('interview_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['interviewId'] === undefined && (value as Record<string, any>)['interview_id'] === undefined)) return false;
    if (!('language' in value) || value['language'] === undefined) return false;
    if (!('turns' in value) || value['turns'] === undefined) return false;
    return true;
}

export function PublicApiInterviewsTranscript200ResponseFromJSON(json: any): PublicApiInterviewsTranscript200Response {
    return PublicApiInterviewsTranscript200ResponseFromJSONTyped(json, false);
}

export function PublicApiInterviewsTranscript200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicApiInterviewsTranscript200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'interviewId': json['interview_id'],
        'language': json['language'],
        'turns': ((json['turns'] as Array<any>).map(PublicApiInterviewsTranscript200ResponseTurnsInnerFromJSON)),
    };
}

export function PublicApiInterviewsTranscript200ResponseToJSON(json: any): PublicApiInterviewsTranscript200Response {
    return PublicApiInterviewsTranscript200ResponseToJSONTyped(json, false);
}

export function PublicApiInterviewsTranscript200ResponseToJSONTyped(value?: PublicApiInterviewsTranscript200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'interview_id': value['interviewId'],
        'language': value['language'],
        'turns': ((value['turns'] as Array<any>).map(PublicApiInterviewsTranscript200ResponseTurnsInnerToJSON)),
    };
}

