/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicInterviewProgressAnyOfInnerAnswersInner
 */
export interface PublicInterviewProgressAnyOfInnerAnswersInner {
    /**
     * 
     */
    answeredAt: string;
    /**
     * 
     */
    questionIndex: number;
}

/**
 * Check if a given object implements the PublicInterviewProgressAnyOfInnerAnswersInner interface.
 */
export function instanceOfPublicInterviewProgressAnyOfInnerAnswersInner(value: object): value is PublicInterviewProgressAnyOfInnerAnswersInner {
    if ((!('answeredAt' in (value as Record<string, any>)) && !('answered_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['answeredAt'] === undefined && (value as Record<string, any>)['answered_at'] === undefined)) return false;
    if ((!('questionIndex' in (value as Record<string, any>)) && !('question_index' in (value as Record<string, any>))) || ((value as Record<string, any>)['questionIndex'] === undefined && (value as Record<string, any>)['question_index'] === undefined)) return false;
    return true;
}

export function PublicInterviewProgressAnyOfInnerAnswersInnerFromJSON(json: any): PublicInterviewProgressAnyOfInnerAnswersInner {
    return PublicInterviewProgressAnyOfInnerAnswersInnerFromJSONTyped(json, false);
}

export function PublicInterviewProgressAnyOfInnerAnswersInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicInterviewProgressAnyOfInnerAnswersInner {
    if (json == null) {
        return json;
    }
    return {
        
        'answeredAt': json['answered_at'],
        'questionIndex': json['question_index'],
    };
}

export function PublicInterviewProgressAnyOfInnerAnswersInnerToJSON(json: any): PublicInterviewProgressAnyOfInnerAnswersInner {
    return PublicInterviewProgressAnyOfInnerAnswersInnerToJSONTyped(json, false);
}

export function PublicInterviewProgressAnyOfInnerAnswersInnerToJSONTyped(value?: PublicInterviewProgressAnyOfInnerAnswersInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'answered_at': value['answeredAt'],
        'question_index': value['questionIndex'],
    };
}

