/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicApiInterviewsStore409ResponseAnyOf
 */
export interface PublicApiInterviewsStore409ResponseAnyOf {
    /**
     * 
     */
    code: PublicApiInterviewsStore409ResponseAnyOfCodeEnum;
    /**
     * 
     */
    detail: PublicApiInterviewsStore409ResponseAnyOfDetailEnum;
    /**
     * 
     */
    errors: string | null;
    /**
     * 
     */
    requestId: string;
    /**
     * 
     */
    status: PublicApiInterviewsStore409ResponseAnyOfStatusEnum;
    /**
     * 
     */
    title: PublicApiInterviewsStore409ResponseAnyOfTitleEnum;
    /**
     * 
     */
    type: string;
}


/**
 * @export
 */
export const PublicApiInterviewsStore409ResponseAnyOfCodeEnum = {
    DuplicateEnrolment: 'duplicate_enrolment',
} as const;
export type PublicApiInterviewsStore409ResponseAnyOfCodeEnum = typeof PublicApiInterviewsStore409ResponseAnyOfCodeEnum[keyof typeof PublicApiInterviewsStore409ResponseAnyOfCodeEnum];

/**
 * @export
 */
export const PublicApiInterviewsStore409ResponseAnyOfDetailEnum = {
    CandidateEmailIsAlreadyEnrolledInThisProject: 'candidate.email is already enrolled in this project.',
} as const;
export type PublicApiInterviewsStore409ResponseAnyOfDetailEnum = typeof PublicApiInterviewsStore409ResponseAnyOfDetailEnum[keyof typeof PublicApiInterviewsStore409ResponseAnyOfDetailEnum];

/**
 * @export
 */
export const PublicApiInterviewsStore409ResponseAnyOfStatusEnum = {
    NUMBER_409: 409,
} as const;
export type PublicApiInterviewsStore409ResponseAnyOfStatusEnum = typeof PublicApiInterviewsStore409ResponseAnyOfStatusEnum[keyof typeof PublicApiInterviewsStore409ResponseAnyOfStatusEnum];

/**
 * @export
 */
export const PublicApiInterviewsStore409ResponseAnyOfTitleEnum = {
    DuplicateEnrolment: 'Duplicate enrolment',
} as const;
export type PublicApiInterviewsStore409ResponseAnyOfTitleEnum = typeof PublicApiInterviewsStore409ResponseAnyOfTitleEnum[keyof typeof PublicApiInterviewsStore409ResponseAnyOfTitleEnum];


/**
 * Check if a given object implements the PublicApiInterviewsStore409ResponseAnyOf interface.
 */
export function instanceOfPublicApiInterviewsStore409ResponseAnyOf(value: object): value is PublicApiInterviewsStore409ResponseAnyOf {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (value['code'] !== 'duplicate_enrolment') return false;
    
    if (!('detail' in value) || value['detail'] === undefined) return false;
    if (value['detail'] !== 'candidate.email is already enrolled in this project.') return false;
    
    if (!('errors' in value) || value['errors'] === undefined) return false;
    if ((!('requestId' in (value as Record<string, any>)) && !('request_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['requestId'] === undefined && (value as Record<string, any>)['request_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    
    if (value['status'] !== 409) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (value['title'] !== 'Duplicate enrolment') return false;
    
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function PublicApiInterviewsStore409ResponseAnyOfFromJSON(json: any): PublicApiInterviewsStore409ResponseAnyOf {
    return PublicApiInterviewsStore409ResponseAnyOfFromJSONTyped(json, false);
}

export function PublicApiInterviewsStore409ResponseAnyOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicApiInterviewsStore409ResponseAnyOf {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'detail': json['detail'],
        'errors': json['errors'],
        'requestId': json['request_id'],
        'status': json['status'],
        'title': json['title'],
        'type': json['type'],
    };
}

export function PublicApiInterviewsStore409ResponseAnyOfToJSON(json: any): PublicApiInterviewsStore409ResponseAnyOf {
    return PublicApiInterviewsStore409ResponseAnyOfToJSONTyped(json, false);
}

export function PublicApiInterviewsStore409ResponseAnyOfToJSONTyped(value?: PublicApiInterviewsStore409ResponseAnyOf | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'detail': value['detail'],
        'errors': value['errors'],
        'request_id': value['requestId'],
        'status': value['status'],
        'title': value['title'],
        'type': value['type'],
    };
}

