/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicApiInterviewsSessionTokensStore201Response
 */
export interface PublicApiInterviewsSessionTokensStore201Response {
    /**
     * 
     */
    expiresAt: string;
    /**
     * 
     */
    hostedUrl: string;
    /**
     * 
     */
    sessionToken: string;
}

/**
 * Check if a given object implements the PublicApiInterviewsSessionTokensStore201Response interface.
 */
export function instanceOfPublicApiInterviewsSessionTokensStore201Response(value: object): value is PublicApiInterviewsSessionTokensStore201Response {
    if ((!('expiresAt' in (value as Record<string, any>)) && !('expires_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['expiresAt'] === undefined && (value as Record<string, any>)['expires_at'] === undefined)) return false;
    if ((!('hostedUrl' in (value as Record<string, any>)) && !('hosted_url' in (value as Record<string, any>))) || ((value as Record<string, any>)['hostedUrl'] === undefined && (value as Record<string, any>)['hosted_url'] === undefined)) return false;
    if ((!('sessionToken' in (value as Record<string, any>)) && !('session_token' in (value as Record<string, any>))) || ((value as Record<string, any>)['sessionToken'] === undefined && (value as Record<string, any>)['session_token'] === undefined)) return false;
    return true;
}

export function PublicApiInterviewsSessionTokensStore201ResponseFromJSON(json: any): PublicApiInterviewsSessionTokensStore201Response {
    return PublicApiInterviewsSessionTokensStore201ResponseFromJSONTyped(json, false);
}

export function PublicApiInterviewsSessionTokensStore201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicApiInterviewsSessionTokensStore201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'expiresAt': json['expires_at'],
        'hostedUrl': json['hosted_url'],
        'sessionToken': json['session_token'],
    };
}

export function PublicApiInterviewsSessionTokensStore201ResponseToJSON(json: any): PublicApiInterviewsSessionTokensStore201Response {
    return PublicApiInterviewsSessionTokensStore201ResponseToJSONTyped(json, false);
}

export function PublicApiInterviewsSessionTokensStore201ResponseToJSONTyped(value?: PublicApiInterviewsSessionTokensStore201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'expires_at': value['expiresAt'],
        'hosted_url': value['hostedUrl'],
        'session_token': value['sessionToken'],
    };
}

