/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PublicApiInterviewsStore409ResponseAnyOf1 } from './PublicApiInterviewsStore409ResponseAnyOf1';
import {
    PublicApiInterviewsStore409ResponseAnyOf1FromJSON,
    PublicApiInterviewsStore409ResponseAnyOf1FromJSONTyped,
    PublicApiInterviewsStore409ResponseAnyOf1ToJSON,
    PublicApiInterviewsStore409ResponseAnyOf1ToJSONTyped,
} from './PublicApiInterviewsStore409ResponseAnyOf1';
import type { PublicApiInterviewsStore409ResponseAnyOf } from './PublicApiInterviewsStore409ResponseAnyOf';
import {
    PublicApiInterviewsStore409ResponseAnyOfFromJSON,
    PublicApiInterviewsStore409ResponseAnyOfFromJSONTyped,
    PublicApiInterviewsStore409ResponseAnyOfToJSON,
    PublicApiInterviewsStore409ResponseAnyOfToJSONTyped,
} from './PublicApiInterviewsStore409ResponseAnyOf';

/**
 * 
 * @export
 * @interface PublicApiInterviewsStore409Response
 */
export interface PublicApiInterviewsStore409Response {
    /**
     * 
     */
    code: PublicApiInterviewsStore409ResponseCodeEnum;
    /**
     * 
     */
    detail: PublicApiInterviewsStore409ResponseDetailEnum;
    /**
     * 
     */
    errors: string;
    /**
     * 
     */
    requestId: string;
    /**
     * 
     */
    status: PublicApiInterviewsStore409ResponseStatusEnum;
    /**
     * 
     */
    title: PublicApiInterviewsStore409ResponseTitleEnum;
    /**
     * 
     */
    type: string;
}


/**
 * @export
 */
export const PublicApiInterviewsStore409ResponseCodeEnum = {
    DuplicateEnrolment: 'duplicate_enrolment',
} as const;
export type PublicApiInterviewsStore409ResponseCodeEnum = typeof PublicApiInterviewsStore409ResponseCodeEnum[keyof typeof PublicApiInterviewsStore409ResponseCodeEnum];

/**
 * @export
 */
export const PublicApiInterviewsStore409ResponseDetailEnum = {
    CandidateCandidateRefIsAlreadyEnrolledInThisProject: 'candidate.candidate_ref is already enrolled in this project.',
} as const;
export type PublicApiInterviewsStore409ResponseDetailEnum = typeof PublicApiInterviewsStore409ResponseDetailEnum[keyof typeof PublicApiInterviewsStore409ResponseDetailEnum];

/**
 * @export
 */
export const PublicApiInterviewsStore409ResponseStatusEnum = {
    NUMBER_409: 409,
} as const;
export type PublicApiInterviewsStore409ResponseStatusEnum = typeof PublicApiInterviewsStore409ResponseStatusEnum[keyof typeof PublicApiInterviewsStore409ResponseStatusEnum];

/**
 * @export
 */
export const PublicApiInterviewsStore409ResponseTitleEnum = {
    DuplicateEnrolment: 'Duplicate enrolment',
} as const;
export type PublicApiInterviewsStore409ResponseTitleEnum = typeof PublicApiInterviewsStore409ResponseTitleEnum[keyof typeof PublicApiInterviewsStore409ResponseTitleEnum];


/**
 * Check if a given object implements the PublicApiInterviewsStore409Response interface.
 */
export function instanceOfPublicApiInterviewsStore409Response(value: object): value is PublicApiInterviewsStore409Response {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (value['code'] !== 'duplicate_enrolment') return false;
    
    if (!('detail' in value) || value['detail'] === undefined) return false;
    if (value['detail'] !== 'candidate.candidate_ref is already enrolled in this project.') return false;
    
    if (!('errors' in value) || value['errors'] === undefined) return false;
    if ((!('requestId' in (value as Record<string, any>)) && !('request_id' in (value as Record<string, any>))) || ((value as Record<string, any>)['requestId'] === undefined && (value as Record<string, any>)['request_id'] === undefined)) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    
    if (value['status'] !== 409) return false;
    if (!('title' in value) || value['title'] === undefined) return false;
    if (value['title'] !== 'Duplicate enrolment') return false;
    
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function PublicApiInterviewsStore409ResponseFromJSON(json: any): PublicApiInterviewsStore409Response {
    return PublicApiInterviewsStore409ResponseFromJSONTyped(json, false);
}

export function PublicApiInterviewsStore409ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicApiInterviewsStore409Response {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'detail': json['detail'],
        'errors': json['errors'],
        'requestId': json['request_id'],
        'status': json['status'],
        'title': json['title'],
        'type': json['type'],
    };
}

export function PublicApiInterviewsStore409ResponseToJSON(json: any): PublicApiInterviewsStore409Response {
    return PublicApiInterviewsStore409ResponseToJSONTyped(json, false);
}

export function PublicApiInterviewsStore409ResponseToJSONTyped(value?: PublicApiInterviewsStore409Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'detail': value['detail'],
        'errors': value['errors'],
        'request_id': value['requestId'],
        'status': value['status'],
        'title': value['title'],
        'type': value['type'],
    };
}

