/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PublicApiInterviewsEvents200ResponseDataInner
 */
export interface PublicApiInterviewsEvents200ResponseDataInner {
    /**
     * 
     */
    data: { [key: string]: any | null; } | null;
    /**
     * 
     */
    id: string;
    /**
     * 
     */
    occurredAt: string;
    /**
     * 
     */
    type: string;
}

/**
 * Check if a given object implements the PublicApiInterviewsEvents200ResponseDataInner interface.
 */
export function instanceOfPublicApiInterviewsEvents200ResponseDataInner(value: object): value is PublicApiInterviewsEvents200ResponseDataInner {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if ((!('occurredAt' in (value as Record<string, any>)) && !('occurred_at' in (value as Record<string, any>))) || ((value as Record<string, any>)['occurredAt'] === undefined && (value as Record<string, any>)['occurred_at'] === undefined)) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    return true;
}

export function PublicApiInterviewsEvents200ResponseDataInnerFromJSON(json: any): PublicApiInterviewsEvents200ResponseDataInner {
    return PublicApiInterviewsEvents200ResponseDataInnerFromJSONTyped(json, false);
}

export function PublicApiInterviewsEvents200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PublicApiInterviewsEvents200ResponseDataInner {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'],
        'id': json['id'],
        'occurredAt': json['occurred_at'],
        'type': json['type'],
    };
}

export function PublicApiInterviewsEvents200ResponseDataInnerToJSON(json: any): PublicApiInterviewsEvents200ResponseDataInner {
    return PublicApiInterviewsEvents200ResponseDataInnerToJSONTyped(json, false);
}

export function PublicApiInterviewsEvents200ResponseDataInnerToJSONTyped(value?: PublicApiInterviewsEvents200ResponseDataInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'],
        'id': value['id'],
        'occurred_at': value['occurredAt'],
        'type': value['type'],
    };
}

