<?php
/**
 * PublicApiInterviewsAnswers200ResponseAnswersInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Beai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BEAI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.68.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Beai\Model;

use \ArrayAccess;
use \Beai\ObjectSerializer;

/**
 * PublicApiInterviewsAnswers200ResponseAnswersInner Class Doc Comment
 *
 * @category Class
 * @package  Beai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PublicApiInterviewsAnswers200ResponseAnswersInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'public_api_interviews_answers_200_response_answers_inner';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'answer_duration_seconds' => 'float',
        'answer_text' => 'string',
        'competency_code' => 'string',
        'question_index' => 'int',
        'question_text' => 'string',
        'started_at_seconds' => 'float'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'answer_duration_seconds' => null,
        'answer_text' => null,
        'competency_code' => null,
        'question_index' => null,
        'question_text' => null,
        'started_at_seconds' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'answer_duration_seconds' => true,
        'answer_text' => false,
        'competency_code' => false,
        'question_index' => false,
        'question_text' => false,
        'started_at_seconds' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'answer_duration_seconds' => 'answer_duration_seconds',
        'answer_text' => 'answer_text',
        'competency_code' => 'competency_code',
        'question_index' => 'question_index',
        'question_text' => 'question_text',
        'started_at_seconds' => 'started_at_seconds'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'answer_duration_seconds' => 'setAnswerDurationSeconds',
        'answer_text' => 'setAnswerText',
        'competency_code' => 'setCompetencyCode',
        'question_index' => 'setQuestionIndex',
        'question_text' => 'setQuestionText',
        'started_at_seconds' => 'setStartedAtSeconds'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'answer_duration_seconds' => 'getAnswerDurationSeconds',
        'answer_text' => 'getAnswerText',
        'competency_code' => 'getCompetencyCode',
        'question_index' => 'getQuestionIndex',
        'question_text' => 'getQuestionText',
        'started_at_seconds' => 'getStartedAtSeconds'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('answer_duration_seconds', $data ?? [], null);
        $this->setIfExists('answer_text', $data ?? [], null);
        $this->setIfExists('competency_code', $data ?? [], null);
        $this->setIfExists('question_index', $data ?? [], null);
        $this->setIfExists('question_text', $data ?? [], null);
        $this->setIfExists('started_at_seconds', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['answer_duration_seconds'] === null && !$this->isNullableSetToNull('answer_duration_seconds')) {
            $invalidProperties[] = "'answer_duration_seconds' is required";
        }
        if ($this->container['answer_text'] === null) {
            $invalidProperties[] = "'answer_text' can't be null";
        }
        if ($this->container['competency_code'] === null) {
            $invalidProperties[] = "'competency_code' can't be null";
        }
        if ($this->container['question_index'] === null) {
            $invalidProperties[] = "'question_index' can't be null";
        }
        if ($this->container['question_text'] === null) {
            $invalidProperties[] = "'question_text' can't be null";
        }
        if ($this->container['started_at_seconds'] === null && !$this->isNullableSetToNull('started_at_seconds')) {
            $invalidProperties[] = "'started_at_seconds' is required";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets answer_duration_seconds
     *
     * @return float|null
     */
    public function getAnswerDurationSeconds()
    {
        return $this->container['answer_duration_seconds'];
    }

    /**
     * Sets answer_duration_seconds
     *
     * @param float|null $answer_duration_seconds answer_duration_seconds
     *
     * @return self
     */
    public function setAnswerDurationSeconds($answer_duration_seconds)
    {
        if (is_null($answer_duration_seconds)) {
            array_push($this->openAPINullablesSetToNull, 'answer_duration_seconds');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('answer_duration_seconds', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['answer_duration_seconds'] = $answer_duration_seconds;

        return $this;
    }

    /**
     * Gets answer_text
     *
     * @return string
     */
    public function getAnswerText()
    {
        return $this->container['answer_text'];
    }

    /**
     * Sets answer_text
     *
     * @param string $answer_text answer_text
     *
     * @return self
     */
    public function setAnswerText($answer_text)
    {
        if (is_null($answer_text)) {
            throw new \InvalidArgumentException('non-nullable answer_text cannot be null');
        }
        $this->container['answer_text'] = $answer_text;

        return $this;
    }

    /**
     * Gets competency_code
     *
     * @return string
     */
    public function getCompetencyCode()
    {
        return $this->container['competency_code'];
    }

    /**
     * Sets competency_code
     *
     * @param string $competency_code competency_code
     *
     * @return self
     */
    public function setCompetencyCode($competency_code)
    {
        if (is_null($competency_code)) {
            throw new \InvalidArgumentException('non-nullable competency_code cannot be null');
        }
        $this->container['competency_code'] = $competency_code;

        return $this;
    }

    /**
     * Gets question_index
     *
     * @return int
     */
    public function getQuestionIndex()
    {
        return $this->container['question_index'];
    }

    /**
     * Sets question_index
     *
     * @param int $question_index question_index
     *
     * @return self
     */
    public function setQuestionIndex($question_index)
    {
        if (is_null($question_index)) {
            throw new \InvalidArgumentException('non-nullable question_index cannot be null');
        }
        $this->container['question_index'] = $question_index;

        return $this;
    }

    /**
     * Gets question_text
     *
     * @return string
     */
    public function getQuestionText()
    {
        return $this->container['question_text'];
    }

    /**
     * Sets question_text
     *
     * @param string $question_text question_text
     *
     * @return self
     */
    public function setQuestionText($question_text)
    {
        if (is_null($question_text)) {
            throw new \InvalidArgumentException('non-nullable question_text cannot be null');
        }
        $this->container['question_text'] = $question_text;

        return $this;
    }

    /**
     * Gets started_at_seconds
     *
     * @return float|null
     */
    public function getStartedAtSeconds()
    {
        return $this->container['started_at_seconds'];
    }

    /**
     * Sets started_at_seconds
     *
     * @param float|null $started_at_seconds started_at_seconds
     *
     * @return self
     */
    public function setStartedAtSeconds($started_at_seconds)
    {
        if (is_null($started_at_seconds)) {
            array_push($this->openAPINullablesSetToNull, 'started_at_seconds');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('started_at_seconds', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['started_at_seconds'] = $started_at_seconds;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


