<?php
/**
 * PublicApiInterviewsScoring200Response
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Beai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BEAI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Beai\Model;

use \ArrayAccess;
use \Beai\ObjectSerializer;

/**
 * PublicApiInterviewsScoring200Response Class Doc Comment
 *
 * @category Class
 * @package  Beai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PublicApiInterviewsScoring200Response implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'public_api_interviews_scoring_200_response';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'competencies' => 'array<string,\Beai\Model\PublicApiInterviewsScoring200ResponseCompetenciesValue>',
        'evaluated_at' => 'string',
        'framework_version' => 'string',
        'interview_id' => 'string',
        'model_version' => 'string',
        'prompt_version' => 'string',
        'status' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'competencies' => null,
        'evaluated_at' => null,
        'framework_version' => null,
        'interview_id' => null,
        'model_version' => null,
        'prompt_version' => null,
        'status' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'competencies' => false,
        'evaluated_at' => false,
        'framework_version' => false,
        'interview_id' => false,
        'model_version' => false,
        'prompt_version' => false,
        'status' => false
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'competencies' => 'competencies',
        'evaluated_at' => 'evaluated_at',
        'framework_version' => 'framework_version',
        'interview_id' => 'interview_id',
        'model_version' => 'model_version',
        'prompt_version' => 'prompt_version',
        'status' => 'status'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'competencies' => 'setCompetencies',
        'evaluated_at' => 'setEvaluatedAt',
        'framework_version' => 'setFrameworkVersion',
        'interview_id' => 'setInterviewId',
        'model_version' => 'setModelVersion',
        'prompt_version' => 'setPromptVersion',
        'status' => 'setStatus'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'competencies' => 'getCompetencies',
        'evaluated_at' => 'getEvaluatedAt',
        'framework_version' => 'getFrameworkVersion',
        'interview_id' => 'getInterviewId',
        'model_version' => 'getModelVersion',
        'prompt_version' => 'getPromptVersion',
        'status' => 'getStatus'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('competencies', $data ?? [], null);
        $this->setIfExists('evaluated_at', $data ?? [], null);
        $this->setIfExists('framework_version', $data ?? [], null);
        $this->setIfExists('interview_id', $data ?? [], null);
        $this->setIfExists('model_version', $data ?? [], null);
        $this->setIfExists('prompt_version', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['competencies'] === null) {
            $invalidProperties[] = "'competencies' can't be null";
        }
        if ($this->container['evaluated_at'] === null) {
            $invalidProperties[] = "'evaluated_at' can't be null";
        }
        if ($this->container['framework_version'] === null) {
            $invalidProperties[] = "'framework_version' can't be null";
        }
        if ($this->container['interview_id'] === null) {
            $invalidProperties[] = "'interview_id' can't be null";
        }
        if ($this->container['model_version'] === null) {
            $invalidProperties[] = "'model_version' can't be null";
        }
        if ($this->container['prompt_version'] === null) {
            $invalidProperties[] = "'prompt_version' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets competencies
     *
     * @return array<string,\Beai\Model\PublicApiInterviewsScoring200ResponseCompetenciesValue>
     */
    public function getCompetencies()
    {
        return $this->container['competencies'];
    }

    /**
     * Sets competencies
     *
     * @param array<string,\Beai\Model\PublicApiInterviewsScoring200ResponseCompetenciesValue> $competencies competencies
     *
     * @return self
     */
    public function setCompetencies($competencies)
    {
        if (is_null($competencies)) {
            throw new \InvalidArgumentException('non-nullable competencies cannot be null');
        }
        $this->container['competencies'] = $competencies;

        return $this;
    }

    /**
     * Gets evaluated_at
     *
     * @return string
     */
    public function getEvaluatedAt()
    {
        return $this->container['evaluated_at'];
    }

    /**
     * Sets evaluated_at
     *
     * @param string $evaluated_at evaluated_at
     *
     * @return self
     */
    public function setEvaluatedAt($evaluated_at)
    {
        if (is_null($evaluated_at)) {
            throw new \InvalidArgumentException('non-nullable evaluated_at cannot be null');
        }
        $this->container['evaluated_at'] = $evaluated_at;

        return $this;
    }

    /**
     * Gets framework_version
     *
     * @return string
     */
    public function getFrameworkVersion()
    {
        return $this->container['framework_version'];
    }

    /**
     * Sets framework_version
     *
     * @param string $framework_version framework_version
     *
     * @return self
     */
    public function setFrameworkVersion($framework_version)
    {
        if (is_null($framework_version)) {
            throw new \InvalidArgumentException('non-nullable framework_version cannot be null');
        }
        $this->container['framework_version'] = $framework_version;

        return $this;
    }

    /**
     * Gets interview_id
     *
     * @return string
     */
    public function getInterviewId()
    {
        return $this->container['interview_id'];
    }

    /**
     * Sets interview_id
     *
     * @param string $interview_id interview_id
     *
     * @return self
     */
    public function setInterviewId($interview_id)
    {
        if (is_null($interview_id)) {
            throw new \InvalidArgumentException('non-nullable interview_id cannot be null');
        }
        $this->container['interview_id'] = $interview_id;

        return $this;
    }

    /**
     * Gets model_version
     *
     * @return string
     */
    public function getModelVersion()
    {
        return $this->container['model_version'];
    }

    /**
     * Sets model_version
     *
     * @param string $model_version model_version
     *
     * @return self
     */
    public function setModelVersion($model_version)
    {
        if (is_null($model_version)) {
            throw new \InvalidArgumentException('non-nullable model_version cannot be null');
        }
        $this->container['model_version'] = $model_version;

        return $this;
    }

    /**
     * Gets prompt_version
     *
     * @return string
     */
    public function getPromptVersion()
    {
        return $this->container['prompt_version'];
    }

    /**
     * Sets prompt_version
     *
     * @param string $prompt_version prompt_version
     *
     * @return self
     */
    public function setPromptVersion($prompt_version)
    {
        if (is_null($prompt_version)) {
            throw new \InvalidArgumentException('non-nullable prompt_version cannot be null');
        }
        $this->container['prompt_version'] = $prompt_version;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


