<?php
/**
 * PublicApiWebhooksDeliveriesIndex200ResponseDataInner
 *
 * PHP version 8.1
 *
 * @category Class
 * @package  Beai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * BEAI
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.68.0
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.25.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace Beai\Model;

use \ArrayAccess;
use \Beai\ObjectSerializer;

/**
 * PublicApiWebhooksDeliveriesIndex200ResponseDataInner Class Doc Comment
 *
 * @category Class
 * @package  Beai
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class PublicApiWebhooksDeliveriesIndex200ResponseDataInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
     * The original name of the model.
     *
     * @var string
     */
    protected static $openAPIModelName = 'public_api_webhooks_deliveries_index_200_response_data_inner';

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @var string[]
     */
    protected static $openAPITypes = [
        'attempt_count' => 'int',
        'candidate_ref' => 'string',
        'created_at' => 'string',
        'delivered_at' => 'string',
        'event_type' => 'string',
        'id' => 'string',
        'interview_id' => 'string',
        'last_attempt_at' => 'string',
        'last_response_status' => 'int',
        'max_attempts' => 'int',
        'next_attempt_at' => 'string',
        'payload_version' => 'string',
        'project_id' => 'string',
        'status' => 'string',
        'target_url' => 'string'
    ];

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @var string[]
     * @phpstan-var array<string, string|null>
     * @psalm-var array<string, string|null>
     */
    protected static $openAPIFormats = [
        'attempt_count' => null,
        'candidate_ref' => null,
        'created_at' => null,
        'delivered_at' => null,
        'event_type' => null,
        'id' => null,
        'interview_id' => null,
        'last_attempt_at' => null,
        'last_response_status' => null,
        'max_attempts' => null,
        'next_attempt_at' => null,
        'payload_version' => null,
        'project_id' => null,
        'status' => null,
        'target_url' => null
    ];

    /**
     * Array of nullable properties. Used for (de)serialization
     *
     * @var boolean[]
     */
    protected static array $openAPINullables = [
        'attempt_count' => false,
        'candidate_ref' => false,
        'created_at' => false,
        'delivered_at' => true,
        'event_type' => false,
        'id' => false,
        'interview_id' => false,
        'last_attempt_at' => true,
        'last_response_status' => true,
        'max_attempts' => false,
        'next_attempt_at' => true,
        'payload_version' => false,
        'project_id' => false,
        'status' => false,
        'target_url' => true
    ];

    /**
     * If a nullable field gets set to null, insert it here
     *
     * @var boolean[]
     */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'attempt_count' => 'attempt_count',
        'candidate_ref' => 'candidate_ref',
        'created_at' => 'created_at',
        'delivered_at' => 'delivered_at',
        'event_type' => 'event_type',
        'id' => 'id',
        'interview_id' => 'interview_id',
        'last_attempt_at' => 'last_attempt_at',
        'last_response_status' => 'last_response_status',
        'max_attempts' => 'max_attempts',
        'next_attempt_at' => 'next_attempt_at',
        'payload_version' => 'payload_version',
        'project_id' => 'project_id',
        'status' => 'status',
        'target_url' => 'target_url'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'attempt_count' => 'setAttemptCount',
        'candidate_ref' => 'setCandidateRef',
        'created_at' => 'setCreatedAt',
        'delivered_at' => 'setDeliveredAt',
        'event_type' => 'setEventType',
        'id' => 'setId',
        'interview_id' => 'setInterviewId',
        'last_attempt_at' => 'setLastAttemptAt',
        'last_response_status' => 'setLastResponseStatus',
        'max_attempts' => 'setMaxAttempts',
        'next_attempt_at' => 'setNextAttemptAt',
        'payload_version' => 'setPayloadVersion',
        'project_id' => 'setProjectId',
        'status' => 'setStatus',
        'target_url' => 'setTargetUrl'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'attempt_count' => 'getAttemptCount',
        'candidate_ref' => 'getCandidateRef',
        'created_at' => 'getCreatedAt',
        'delivered_at' => 'getDeliveredAt',
        'event_type' => 'getEventType',
        'id' => 'getId',
        'interview_id' => 'getInterviewId',
        'last_attempt_at' => 'getLastAttemptAt',
        'last_response_status' => 'getLastResponseStatus',
        'max_attempts' => 'getMaxAttempts',
        'next_attempt_at' => 'getNextAttemptAt',
        'payload_version' => 'getPayloadVersion',
        'project_id' => 'getProjectId',
        'status' => 'getStatus',
        'target_url' => 'getTargetUrl'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('attempt_count', $data ?? [], null);
        $this->setIfExists('candidate_ref', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('delivered_at', $data ?? [], null);
        $this->setIfExists('event_type', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('interview_id', $data ?? [], null);
        $this->setIfExists('last_attempt_at', $data ?? [], null);
        $this->setIfExists('last_response_status', $data ?? [], null);
        $this->setIfExists('max_attempts', $data ?? [], null);
        $this->setIfExists('next_attempt_at', $data ?? [], null);
        $this->setIfExists('payload_version', $data ?? [], null);
        $this->setIfExists('project_id', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('target_url', $data ?? [], null);
    }

    /**
     * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
     * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
     * $this->openAPINullablesSetToNull array
     *
     * @param string $variableName
     * @param array  $fields
     * @param mixed  $defaultValue
     */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['attempt_count'] === null) {
            $invalidProperties[] = "'attempt_count' can't be null";
        }
        if ($this->container['candidate_ref'] === null) {
            $invalidProperties[] = "'candidate_ref' can't be null";
        }
        if ($this->container['created_at'] === null) {
            $invalidProperties[] = "'created_at' can't be null";
        }
        if ($this->container['delivered_at'] === null && !$this->isNullableSetToNull('delivered_at')) {
            $invalidProperties[] = "'delivered_at' is required";
        }
        if ($this->container['event_type'] === null) {
            $invalidProperties[] = "'event_type' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        if ($this->container['interview_id'] === null) {
            $invalidProperties[] = "'interview_id' can't be null";
        }
        if ($this->container['last_attempt_at'] === null && !$this->isNullableSetToNull('last_attempt_at')) {
            $invalidProperties[] = "'last_attempt_at' is required";
        }
        if ($this->container['last_response_status'] === null && !$this->isNullableSetToNull('last_response_status')) {
            $invalidProperties[] = "'last_response_status' is required";
        }
        if ($this->container['max_attempts'] === null) {
            $invalidProperties[] = "'max_attempts' can't be null";
        }
        if ($this->container['next_attempt_at'] === null && !$this->isNullableSetToNull('next_attempt_at')) {
            $invalidProperties[] = "'next_attempt_at' is required";
        }
        if ($this->container['payload_version'] === null) {
            $invalidProperties[] = "'payload_version' can't be null";
        }
        if ($this->container['project_id'] === null) {
            $invalidProperties[] = "'project_id' can't be null";
        }
        if ($this->container['status'] === null) {
            $invalidProperties[] = "'status' can't be null";
        }
        if ($this->container['target_url'] === null && !$this->isNullableSetToNull('target_url')) {
            $invalidProperties[] = "'target_url' is required";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets attempt_count
     *
     * @return int
     */
    public function getAttemptCount()
    {
        return $this->container['attempt_count'];
    }

    /**
     * Sets attempt_count
     *
     * @param int $attempt_count attempt_count
     *
     * @return self
     */
    public function setAttemptCount($attempt_count)
    {
        if (is_null($attempt_count)) {
            throw new \InvalidArgumentException('non-nullable attempt_count cannot be null');
        }
        $this->container['attempt_count'] = $attempt_count;

        return $this;
    }

    /**
     * Gets candidate_ref
     *
     * @return string
     */
    public function getCandidateRef()
    {
        return $this->container['candidate_ref'];
    }

    /**
     * Sets candidate_ref
     *
     * @param string $candidate_ref candidate_ref
     *
     * @return self
     */
    public function setCandidateRef($candidate_ref)
    {
        if (is_null($candidate_ref)) {
            throw new \InvalidArgumentException('non-nullable candidate_ref cannot be null');
        }
        $this->container['candidate_ref'] = $candidate_ref;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return string
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param string $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets delivered_at
     *
     * @return string|null
     */
    public function getDeliveredAt()
    {
        return $this->container['delivered_at'];
    }

    /**
     * Sets delivered_at
     *
     * @param string|null $delivered_at delivered_at
     *
     * @return self
     */
    public function setDeliveredAt($delivered_at)
    {
        if (is_null($delivered_at)) {
            array_push($this->openAPINullablesSetToNull, 'delivered_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('delivered_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['delivered_at'] = $delivered_at;

        return $this;
    }

    /**
     * Gets event_type
     *
     * @return string
     */
    public function getEventType()
    {
        return $this->container['event_type'];
    }

    /**
     * Sets event_type
     *
     * @param string $event_type event_type
     *
     * @return self
     */
    public function setEventType($event_type)
    {
        if (is_null($event_type)) {
            throw new \InvalidArgumentException('non-nullable event_type cannot be null');
        }
        $this->container['event_type'] = $event_type;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets interview_id
     *
     * @return string
     */
    public function getInterviewId()
    {
        return $this->container['interview_id'];
    }

    /**
     * Sets interview_id
     *
     * @param string $interview_id interview_id
     *
     * @return self
     */
    public function setInterviewId($interview_id)
    {
        if (is_null($interview_id)) {
            throw new \InvalidArgumentException('non-nullable interview_id cannot be null');
        }
        $this->container['interview_id'] = $interview_id;

        return $this;
    }

    /**
     * Gets last_attempt_at
     *
     * @return string|null
     */
    public function getLastAttemptAt()
    {
        return $this->container['last_attempt_at'];
    }

    /**
     * Sets last_attempt_at
     *
     * @param string|null $last_attempt_at last_attempt_at
     *
     * @return self
     */
    public function setLastAttemptAt($last_attempt_at)
    {
        if (is_null($last_attempt_at)) {
            array_push($this->openAPINullablesSetToNull, 'last_attempt_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_attempt_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_attempt_at'] = $last_attempt_at;

        return $this;
    }

    /**
     * Gets last_response_status
     *
     * @return int|null
     */
    public function getLastResponseStatus()
    {
        return $this->container['last_response_status'];
    }

    /**
     * Sets last_response_status
     *
     * @param int|null $last_response_status last_response_status
     *
     * @return self
     */
    public function setLastResponseStatus($last_response_status)
    {
        if (is_null($last_response_status)) {
            array_push($this->openAPINullablesSetToNull, 'last_response_status');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('last_response_status', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['last_response_status'] = $last_response_status;

        return $this;
    }

    /**
     * Gets max_attempts
     *
     * @return int
     */
    public function getMaxAttempts()
    {
        return $this->container['max_attempts'];
    }

    /**
     * Sets max_attempts
     *
     * @param int $max_attempts max_attempts
     *
     * @return self
     */
    public function setMaxAttempts($max_attempts)
    {
        if (is_null($max_attempts)) {
            throw new \InvalidArgumentException('non-nullable max_attempts cannot be null');
        }
        $this->container['max_attempts'] = $max_attempts;

        return $this;
    }

    /**
     * Gets next_attempt_at
     *
     * @return string|null
     */
    public function getNextAttemptAt()
    {
        return $this->container['next_attempt_at'];
    }

    /**
     * Sets next_attempt_at
     *
     * @param string|null $next_attempt_at next_attempt_at
     *
     * @return self
     */
    public function setNextAttemptAt($next_attempt_at)
    {
        if (is_null($next_attempt_at)) {
            array_push($this->openAPINullablesSetToNull, 'next_attempt_at');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('next_attempt_at', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['next_attempt_at'] = $next_attempt_at;

        return $this;
    }

    /**
     * Gets payload_version
     *
     * @return string
     */
    public function getPayloadVersion()
    {
        return $this->container['payload_version'];
    }

    /**
     * Sets payload_version
     *
     * @param string $payload_version payload_version
     *
     * @return self
     */
    public function setPayloadVersion($payload_version)
    {
        if (is_null($payload_version)) {
            throw new \InvalidArgumentException('non-nullable payload_version cannot be null');
        }
        $this->container['payload_version'] = $payload_version;

        return $this;
    }

    /**
     * Gets project_id
     *
     * @return string
     */
    public function getProjectId()
    {
        return $this->container['project_id'];
    }

    /**
     * Sets project_id
     *
     * @param string $project_id project_id
     *
     * @return self
     */
    public function setProjectId($project_id)
    {
        if (is_null($project_id)) {
            throw new \InvalidArgumentException('non-nullable project_id cannot be null');
        }
        $this->container['project_id'] = $project_id;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets target_url
     *
     * @return string|null
     */
    public function getTargetUrl()
    {
        return $this->container['target_url'];
    }

    /**
     * Sets target_url
     *
     * @param string|null $target_url target_url
     *
     * @return self
     */
    public function setTargetUrl($target_url)
    {
        if (is_null($target_url)) {
            array_push($this->openAPINullablesSetToNull, 'target_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('target_url', $nullablesSetToNull);
            if ($index !== FALSE) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['target_url'] = $target_url;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer|string $offset Offset
     *
     * @return boolean
     */
    public function offsetExists(mixed $offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet(mixed $offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer|string $offset Offset
     *
     * @return void
     */
    public function offsetUnset(mixed $offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


