/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type CreateInterviewRequest,
    CreateInterviewRequestFromJSON,
    CreateInterviewRequestToJSON,
} from '../models/CreateInterviewRequest';
import {
    type InlineObject,
    InlineObjectFromJSON,
    InlineObjectToJSON,
} from '../models/InlineObject';
import {
    type InlineObject1,
    InlineObject1FromJSON,
    InlineObject1ToJSON,
} from '../models/InlineObject1';
import {
    type PublicApiExportsIndex400Response,
    PublicApiExportsIndex400ResponseFromJSON,
    PublicApiExportsIndex400ResponseToJSON,
} from '../models/PublicApiExportsIndex400Response';
import {
    type PublicApiInterviewsAnswers200Response,
    PublicApiInterviewsAnswers200ResponseFromJSON,
    PublicApiInterviewsAnswers200ResponseToJSON,
} from '../models/PublicApiInterviewsAnswers200Response';
import {
    type PublicApiInterviewsEvents200Response,
    PublicApiInterviewsEvents200ResponseFromJSON,
    PublicApiInterviewsEvents200ResponseToJSON,
} from '../models/PublicApiInterviewsEvents200Response';
import {
    type PublicApiInterviewsIndex200Response,
    PublicApiInterviewsIndex200ResponseFromJSON,
    PublicApiInterviewsIndex200ResponseToJSON,
} from '../models/PublicApiInterviewsIndex200Response';
import {
    type PublicApiInterviewsScoring200Response,
    PublicApiInterviewsScoring200ResponseFromJSON,
    PublicApiInterviewsScoring200ResponseToJSON,
} from '../models/PublicApiInterviewsScoring200Response';
import {
    type PublicApiInterviewsStore201Response,
    PublicApiInterviewsStore201ResponseFromJSON,
    PublicApiInterviewsStore201ResponseToJSON,
} from '../models/PublicApiInterviewsStore201Response';
import {
    type PublicApiInterviewsStore409Response,
    PublicApiInterviewsStore409ResponseFromJSON,
    PublicApiInterviewsStore409ResponseToJSON,
} from '../models/PublicApiInterviewsStore409Response';
import {
    type PublicApiInterviewsTranscript200Response,
    PublicApiInterviewsTranscript200ResponseFromJSON,
    PublicApiInterviewsTranscript200ResponseToJSON,
} from '../models/PublicApiInterviewsTranscript200Response';
import {
    type PublicInterview,
    PublicInterviewFromJSON,
    PublicInterviewToJSON,
} from '../models/PublicInterview';

export interface PublicApiInterviewsAnswersRequest {
    /**
     * 
     */
    interview: string;
}

export interface PublicApiInterviewsEventsRequest {
    /**
     * 
     */
    interview: string;
    /**
     * Opaque pagination cursor from a previous page's next_cursor. Omit for the first page. A present but malformed value answers 400 invalid_cursor.
     */
    cursor?: string;
    /**
     * Page size, 1-100 (default 25). Out of range answers 400 validation_failed.
     */
    limit?: number;
}

export interface PublicApiInterviewsIndexRequest {
    /**
     * 
     */
    status?: string;
    /**
     * 
     */
    projectId?: string;
    /**
     * 
     */
    email?: string;
    /**
     * 
     */
    candidateRef?: string;
    /**
     * 
     */
    metadata?: string;
    /**
     * Inclusive lower bound on created_at. Strict ISO 8601 date-time, UTC (Z) or a numeric offset, e.g. 2026-01-01T00:00:00Z. An invalid or non-ISO-8601 value answers 400 validation_failed.
     */
    createdAfter?: string;
    /**
     * Exclusive upper bound on created_at. Strict ISO 8601 date-time, UTC (Z) or a numeric offset, e.g. 2026-01-01T00:00:00Z. An invalid or non-ISO-8601 value answers 400 validation_failed.
     */
    createdBefore?: string;
    /**
     * Opaque pagination cursor from a previous page's next_cursor. Omit for the first page. A present but malformed value answers 400 invalid_cursor.
     */
    cursor?: string;
    /**
     * Page size, 1-100 (default 25). Out of range answers 400 validation_failed.
     */
    limit?: number;
    /**
     * Exact match on the external_id supplied as candidate.external_id when the interview was created. An integer from 1 to 9007199254740991; any other value answers 400 validation_failed. An empty value is ignored.
     */
    externalId?: number;
    /**
     * Exact, case-sensitive match on the source supplied as candidate.source when the interview was created. At most 180 characters; a longer value answers 400 validation_failed. An empty value is ignored.
     */
    source?: string;
    /**
     * Comma-separated related resources to inline. Supported: project.
     */
    expand?: string;
}

export interface PublicApiInterviewsScoringRequest {
    /**
     * 
     */
    interview: string;
}

export interface PublicApiInterviewsShowRequest {
    /**
     * 
     */
    interview: string;
    /**
     * Comma-separated related resources to inline. Supported: project.
     */
    expand?: string;
}

export interface PublicApiInterviewsStoreRequest {
    /**
     * 
     */
    createInterviewRequest: CreateInterviewRequest;
}

export interface PublicApiInterviewsTranscriptRequest {
    /**
     * 
     */
    interview: string;
}

/**
 * 
 */
export class InterviewApi extends runtime.BaseAPI {

    /**
     * Creates request options for publicApiInterviewsAnswers without sending the request
     */
    async publicApiInterviewsAnswersRequestOpts(requestParameters: PublicApiInterviewsAnswersRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['interview'] == null) {
            throw new runtime.RequiredError(
                'interview',
                'Required parameter "interview" was null or undefined when calling publicApiInterviewsAnswers().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/interviews/{interview}/answers`;
        urlPath = urlPath.replace('{interview}', encodeURIComponent(String(requestParameters['interview'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Readable under the same conditions as the transcript: once the interview is under evaluation or completed, otherwise `409 transcript_not_ready`.
     * Get the answers
     */
    async publicApiInterviewsAnswersRaw(requestParameters: PublicApiInterviewsAnswersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicApiInterviewsAnswers200Response>> {
        const requestOptions = await this.publicApiInterviewsAnswersRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicApiInterviewsAnswers200ResponseFromJSON(jsonValue));
    }

    /**
     * Readable under the same conditions as the transcript: once the interview is under evaluation or completed, otherwise `409 transcript_not_ready`.
     * Get the answers
     */
    async publicApiInterviewsAnswers(requestParameters: PublicApiInterviewsAnswersRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicApiInterviewsAnswers200Response> {
        const response = await this.publicApiInterviewsAnswersRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicApiInterviewsEvents without sending the request
     */
    async publicApiInterviewsEventsRequestOpts(requestParameters: PublicApiInterviewsEventsRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['interview'] == null) {
            throw new runtime.RequiredError(
                'interview',
                'Required parameter "interview" was null or undefined when calling publicApiInterviewsEvents().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/interviews/{interview}/events`;
        urlPath = urlPath.replace('{interview}', encodeURIComponent(String(requestParameters['interview'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the events of one interview in cursor-paginated pages, oldest first. This is the one list ordered ascending, by the time each event occurred, rather than newest first.
     * List interview events
     */
    async publicApiInterviewsEventsRaw(requestParameters: PublicApiInterviewsEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicApiInterviewsEvents200Response>> {
        const requestOptions = await this.publicApiInterviewsEventsRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicApiInterviewsEvents200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns the events of one interview in cursor-paginated pages, oldest first. This is the one list ordered ascending, by the time each event occurred, rather than newest first.
     * List interview events
     */
    async publicApiInterviewsEvents(requestParameters: PublicApiInterviewsEventsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicApiInterviewsEvents200Response> {
        const response = await this.publicApiInterviewsEventsRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicApiInterviewsIndex without sending the request
     */
    async publicApiInterviewsIndexRequestOpts(requestParameters: PublicApiInterviewsIndexRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['projectId'] != null) {
            queryParameters['project_id'] = requestParameters['projectId'];
        }

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        if (requestParameters['candidateRef'] != null) {
            queryParameters['candidate_ref'] = requestParameters['candidateRef'];
        }

        if (requestParameters['metadata'] != null) {
            queryParameters['metadata'] = requestParameters['metadata'];
        }

        if (requestParameters['createdAfter'] != null) {
            queryParameters['created_after'] = requestParameters['createdAfter'];
        }

        if (requestParameters['createdBefore'] != null) {
            queryParameters['created_before'] = requestParameters['createdBefore'];
        }

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['externalId'] != null) {
            queryParameters['external_id'] = requestParameters['externalId'];
        }

        if (requestParameters['source'] != null) {
            queryParameters['source'] = requestParameters['source'];
        }

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/interviews`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the organization\'s interviews for the mode of the API key, newest first, in cursor-paginated pages. Every filter is optional: a filter sent with an empty value is treated as not provided, and the unfiltered list is returned.
     * List interviews
     */
    async publicApiInterviewsIndexRaw(requestParameters: PublicApiInterviewsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicApiInterviewsIndex200Response>> {
        const requestOptions = await this.publicApiInterviewsIndexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicApiInterviewsIndex200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns the organization\'s interviews for the mode of the API key, newest first, in cursor-paginated pages. Every filter is optional: a filter sent with an empty value is treated as not provided, and the unfiltered list is returned.
     * List interviews
     */
    async publicApiInterviewsIndex(requestParameters: PublicApiInterviewsIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicApiInterviewsIndex200Response> {
        const response = await this.publicApiInterviewsIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicApiInterviewsScoring without sending the request
     */
    async publicApiInterviewsScoringRequestOpts(requestParameters: PublicApiInterviewsScoringRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['interview'] == null) {
            throw new runtime.RequiredError(
                'interview',
                'Required parameter "interview" was null or undefined when calling publicApiInterviewsScoring().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/interviews/{interview}/scoring`;
        urlPath = urlPath.replace('{interview}', encodeURIComponent(String(requestParameters['interview'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Readable only once the interview is completed, otherwise `409 scoring_not_ready`.
     * Get the scoring
     */
    async publicApiInterviewsScoringRaw(requestParameters: PublicApiInterviewsScoringRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicApiInterviewsScoring200Response>> {
        const requestOptions = await this.publicApiInterviewsScoringRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicApiInterviewsScoring200ResponseFromJSON(jsonValue));
    }

    /**
     * Readable only once the interview is completed, otherwise `409 scoring_not_ready`.
     * Get the scoring
     */
    async publicApiInterviewsScoring(requestParameters: PublicApiInterviewsScoringRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicApiInterviewsScoring200Response> {
        const response = await this.publicApiInterviewsScoringRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicApiInterviewsShow without sending the request
     */
    async publicApiInterviewsShowRequestOpts(requestParameters: PublicApiInterviewsShowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['interview'] == null) {
            throw new runtime.RequiredError(
                'interview',
                'Required parameter "interview" was null or undefined when calling publicApiInterviewsShow().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['expand'] != null) {
            queryParameters['expand'] = requestParameters['expand'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/interviews/{interview}`;
        urlPath = urlPath.replace('{interview}', encodeURIComponent(String(requestParameters['interview'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async publicApiInterviewsShowRaw(requestParameters: PublicApiInterviewsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicInterview>> {
        const requestOptions = await this.publicApiInterviewsShowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicInterviewFromJSON(jsonValue));
    }

    /**
     */
    async publicApiInterviewsShow(requestParameters: PublicApiInterviewsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicInterview> {
        const response = await this.publicApiInterviewsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicApiInterviewsStore without sending the request
     */
    async publicApiInterviewsStoreRequestOpts(requestParameters: PublicApiInterviewsStoreRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['createInterviewRequest'] == null) {
            throw new runtime.RequiredError(
                'createInterviewRequest',
                'Required parameter "createInterviewRequest" was null or undefined when calling publicApiInterviewsStore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/interviews`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateInterviewRequestToJSON(requestParameters['createInterviewRequest']),
        };
    }

    /**
     * Enrols a candidate on an active project. The response carries the new interview, a short-lived session token and the URL of the hosted interview.
     * Create an interview
     */
    async publicApiInterviewsStoreRaw(requestParameters: PublicApiInterviewsStoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicApiInterviewsStore201Response>> {
        const requestOptions = await this.publicApiInterviewsStoreRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicApiInterviewsStore201ResponseFromJSON(jsonValue));
    }

    /**
     * Enrols a candidate on an active project. The response carries the new interview, a short-lived session token and the URL of the hosted interview.
     * Create an interview
     */
    async publicApiInterviewsStore(requestParameters: PublicApiInterviewsStoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicApiInterviewsStore201Response> {
        const response = await this.publicApiInterviewsStoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicApiInterviewsTranscript without sending the request
     */
    async publicApiInterviewsTranscriptRequestOpts(requestParameters: PublicApiInterviewsTranscriptRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['interview'] == null) {
            throw new runtime.RequiredError(
                'interview',
                'Required parameter "interview" was null or undefined when calling publicApiInterviewsTranscript().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/interviews/{interview}/transcript`;
        urlPath = urlPath.replace('{interview}', encodeURIComponent(String(requestParameters['interview'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Readable once the interview is under evaluation or completed. Before that, and for an interview that ended in error, the response is `409 transcript_not_ready`.
     * Get the transcript
     */
    async publicApiInterviewsTranscriptRaw(requestParameters: PublicApiInterviewsTranscriptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicApiInterviewsTranscript200Response>> {
        const requestOptions = await this.publicApiInterviewsTranscriptRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicApiInterviewsTranscript200ResponseFromJSON(jsonValue));
    }

    /**
     * Readable once the interview is under evaluation or completed. Before that, and for an interview that ended in error, the response is `409 transcript_not_ready`.
     * Get the transcript
     */
    async publicApiInterviewsTranscript(requestParameters: PublicApiInterviewsTranscriptRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicApiInterviewsTranscript200Response> {
        const response = await this.publicApiInterviewsTranscriptRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
