/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.68.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type InlineObject,
    InlineObjectFromJSON,
    InlineObjectToJSON,
} from '../models/InlineObject';
import {
    type PublicApiExportsIndex400Response,
    PublicApiExportsIndex400ResponseFromJSON,
    PublicApiExportsIndex400ResponseToJSON,
} from '../models/PublicApiExportsIndex400Response';
import {
    type PublicApiProjectsIndex200Response,
    PublicApiProjectsIndex200ResponseFromJSON,
    PublicApiProjectsIndex200ResponseToJSON,
} from '../models/PublicApiProjectsIndex200Response';
import {
    type PublicProject,
    PublicProjectFromJSON,
    PublicProjectToJSON,
} from '../models/PublicProject';

export interface PublicApiProjectsIndexRequest {
    /**
     * Opaque pagination cursor from a previous page's next_cursor. Omit for the first page. A present but malformed value answers 400 invalid_cursor.
     */
    cursor?: string;
    /**
     * Page size, 1-100 (default 25). Out of range answers 400 validation_failed.
     */
    limit?: number;
    /**
     * Filter by project status.
     */
    status?: string;
    /**
     * Filter by role code (ICO, FLL, MLL, BUL, SRX).
     */
    roleCode?: string;
    /**
     * Filter by assessment type (standard or potential).
     */
    assessmentType?: string;
}

export interface PublicApiProjectsShowRequest {
    /**
     * 
     */
    project: string;
}

/**
 * 
 */
export class ProjectApi extends runtime.BaseAPI {

    /**
     * Creates request options for publicApiProjectsIndex without sending the request
     */
    async publicApiProjectsIndexRequestOpts(requestParameters: PublicApiProjectsIndexRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['cursor'] != null) {
            queryParameters['cursor'] = requestParameters['cursor'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['status'] != null) {
            queryParameters['status'] = requestParameters['status'];
        }

        if (requestParameters['roleCode'] != null) {
            queryParameters['role_code'] = requestParameters['roleCode'];
        }

        if (requestParameters['assessmentType'] != null) {
            queryParameters['assessment_type'] = requestParameters['assessmentType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Returns the organization\'s projects in cursor-paginated pages, newest first. The `status`, `role_code` and `assessment_type` filters are optional: an empty value is treated as not provided, and an unrecognised value answers `400 validation_failed`.
     * List projects
     */
    async publicApiProjectsIndexRaw(requestParameters: PublicApiProjectsIndexRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicApiProjectsIndex200Response>> {
        const requestOptions = await this.publicApiProjectsIndexRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicApiProjectsIndex200ResponseFromJSON(jsonValue));
    }

    /**
     * Returns the organization\'s projects in cursor-paginated pages, newest first. The `status`, `role_code` and `assessment_type` filters are optional: an empty value is treated as not provided, and an unrecognised value answers `400 validation_failed`.
     * List projects
     */
    async publicApiProjectsIndex(requestParameters: PublicApiProjectsIndexRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicApiProjectsIndex200Response> {
        const response = await this.publicApiProjectsIndexRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for publicApiProjectsShow without sending the request
     */
    async publicApiProjectsShowRequestOpts(requestParameters: PublicApiProjectsShowRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['project'] == null) {
            throw new runtime.RequiredError(
                'project',
                'Required parameter "project" was null or undefined when calling publicApiProjectsShow().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/projects/{project}`;
        urlPath = urlPath.replace('{project}', encodeURIComponent(String(requestParameters['project'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * A project id that is malformed or unknown answers `404 not_found`.
     * Get a project
     */
    async publicApiProjectsShowRaw(requestParameters: PublicApiProjectsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicProject>> {
        const requestOptions = await this.publicApiProjectsShowRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicProjectFromJSON(jsonValue));
    }

    /**
     * A project id that is malformed or unknown answers `404 not_found`.
     * Get a project
     */
    async publicApiProjectsShow(requestParameters: PublicApiProjectsShowRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicProject> {
        const response = await this.publicApiProjectsShowRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
