/* tslint:disable */
/* eslint-disable */
/**
 * BEAI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.67.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type InlineObject,
    InlineObjectFromJSON,
    InlineObjectToJSON,
} from '../models/InlineObject';
import {
    type PublicApiInterviewsSessionTokensStore201Response,
    PublicApiInterviewsSessionTokensStore201ResponseFromJSON,
    PublicApiInterviewsSessionTokensStore201ResponseToJSON,
} from '../models/PublicApiInterviewsSessionTokensStore201Response';
import {
    type PublicApiInterviewsSessionTokensStore409Response,
    PublicApiInterviewsSessionTokensStore409ResponseFromJSON,
    PublicApiInterviewsSessionTokensStore409ResponseToJSON,
} from '../models/PublicApiInterviewsSessionTokensStore409Response';

export interface PublicApiInterviewsSessionTokensStoreRequest {
    /**
     * 
     */
    interview: string;
}

/**
 * 
 */
export class SessionTokenApi extends runtime.BaseAPI {

    /**
     * Creates request options for publicApiInterviewsSessionTokensStore without sending the request
     */
    async publicApiInterviewsSessionTokensStoreRequestOpts(requestParameters: PublicApiInterviewsSessionTokensStoreRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['interview'] == null) {
            throw new runtime.RequiredError(
                'interview',
                'Required parameter "interview" was null or undefined when calling publicApiInterviewsSessionTokensStore().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("apiKey", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }

        let urlPath = `/interviews/{interview}/session-tokens`;
        urlPath = urlPath.replace('{interview}', encodeURIComponent(String(requestParameters['interview'])));

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     */
    async publicApiInterviewsSessionTokensStoreRaw(requestParameters: PublicApiInterviewsSessionTokensStoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PublicApiInterviewsSessionTokensStore201Response>> {
        const requestOptions = await this.publicApiInterviewsSessionTokensStoreRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PublicApiInterviewsSessionTokensStore201ResponseFromJSON(jsonValue));
    }

    /**
     */
    async publicApiInterviewsSessionTokensStore(requestParameters: PublicApiInterviewsSessionTokensStoreRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PublicApiInterviewsSessionTokensStore201Response> {
        const response = await this.publicApiInterviewsSessionTokensStoreRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
